// *****************************************************************************
//
// This file is part of a MASA library or program.
// Refer to the included end-user license agreement for restrictions.
//
// Copyright (c) 2020 MASA Group
//
// *****************************************************************************

// *****************************************************************************
//
// Warning: This file was generated by soft.generator.go Generator
//
// *****************************************************************************

package ecore

type MockEAttribute struct {
	MockEStructuralFeature
}

// GetEAttributeType get the value of eAttributeType
func (eAttribute *MockEAttribute) GetEAttributeType() EDataType {
	ret := eAttribute.Called()

	var r EDataType
	if rf, ok := ret.Get(0).(func() EDataType); ok {
		r = rf()
	} else {
		if ret.Get(0) != nil {
			r = ret.Get(0).(EDataType)
		}
	}

	return r
}

// IsID get the value of isID
func (eAttribute *MockEAttribute) IsID() bool {
	ret := eAttribute.Called()

	var r bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r = rf()
	} else {
		if ret.Get(0) != nil {
			r = ret.Get(0).(bool)
		}
	}

	return r
}

// SetID provides mock implementation for setting the value of isID
func (eAttribute *MockEAttribute) SetID(newIsID bool) {
	eAttribute.Called(newIsID)
}
