// *****************************************************************************
//
// This file is part of a MASA library or program.
// Refer to the included end-user license agreement for restrictions.
//
// Copyright (c) 2020 MASA Group
//
// *****************************************************************************

// *****************************************************************************
//
// Warning: This file was generated by soft.generator.go Generator
//
// *****************************************************************************

package ecore

import (
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"reflect"
	"testing"
)

func discardEClassifier() {
	_ = assert.Equal
	_ = mock.Anything
	_ = testing.Coverage

}

func TestEClassifierInstanceClassGet(t *testing.T) {
	var newValue reflect.Type = nil
	obj := newEClassifierImpl()
	obj.SetInstanceClass(newValue)
	assert.Equal(t, newValue, obj.GetInstanceClass())
}

func TestEClassifierInstanceClassSet(t *testing.T) {
	var newValue reflect.Type = nil
	obj := newEClassifierImpl()
	mockAdapter := &MockEAdapter{}
	mockAdapter.On("SetTarget", obj).Once()
	mockAdapter.On("NotifyChanged", mock.Anything).Once()
	obj.EAdapters().Add(mockAdapter)
	obj.SetInstanceClass(newValue)
	mockAdapter.AssertExpectations(t)
}

func TestEClassifierClassifierIDGet(t *testing.T) {
	var newValue int = 45
	obj := newEClassifierImpl()
	obj.SetClassifierID(newValue)
	assert.Equal(t, newValue, obj.GetClassifierID())
}

func TestEClassifierClassifierIDSet(t *testing.T) {
	var newValue int = 45
	obj := newEClassifierImpl()
	mockAdapter := &MockEAdapter{}
	mockAdapter.On("SetTarget", obj).Once()
	mockAdapter.On("NotifyChanged", mock.Anything).Once()
	obj.EAdapters().Add(mockAdapter)
	obj.SetClassifierID(newValue)
	mockAdapter.AssertExpectations(t)
}

func TestEClassifierIsInstanceOperation(t *testing.T) {
	obj := newEClassifierImpl()
	assert.Panics(t, func() { obj.IsInstance(nil) })
}
