// Code generated by soft.generator.go. DO NOT EDIT.

// *****************************************************************************
// Copyright(c) 2021 MASA Group
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// *****************************************************************************

package ecore

import "reflect"

// EClassifier is the representation of the model object 'EClassifier'
type EClassifier interface {
	ENamedElement

	IsInstance(interface{}) bool

	GetInstanceTypeName() string
	SetInstanceTypeName(string)

	GetInstanceClass() reflect.Type
	SetInstanceClass(reflect.Type)

	GetDefaultValue() interface{}

	GetClassifierID() int
	SetClassifierID(int)

	GetEPackage() EPackage

	// Start of user code EClassifier
	// End of user code
}
