// Code generated by soft.generator.go. DO NOT EDIT.

// *****************************************************************************
// Copyright(c) 2021 MASA Group
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// *****************************************************************************

package ecore

type EcoreFactory interface {
	EFactory
	CreateEAnnotation() EAnnotation
	CreateEAnnotationFromContainer(eContainer EModelElement) EAnnotation
	CreateEAttribute() EAttribute
	CreateEAttributeFromContainer(eContainer EClass) EAttribute
	CreateEAttributeFromContainerAndClassID(eContainer EClass, classID int) EAttribute
	CreateEClass() EClass
	CreateEClassFromContainer(eContainer EPackage) EClass
	CreateEClassFromContainerAndClassID(eContainer EPackage, classID int) EClass
	CreateEDataType() EDataType
	CreateEDataTypeFromContainer(eContainer EPackage) EDataType
	CreateEDataTypeFromContainerAndClassID(eContainer EPackage, classID int) EDataType
	CreateEEnum() EEnum
	CreateEEnumFromContainer(eContainer EPackage) EEnum
	CreateEEnumFromContainerAndClassID(eContainer EPackage, classID int) EEnum
	CreateEEnumLiteral() EEnumLiteral
	CreateEEnumLiteralFromContainer(eContainer EEnum) EEnumLiteral
	CreateEFactory() EFactory
	CreateEFactoryFromContainer(eContainer EPackage) EFactory
	CreateEGenericType() EGenericType
	CreateEObject() EObject
	CreateEOperation() EOperation
	CreateEOperationFromContainer(eContainer EClass) EOperation
	CreateEOperationFromContainerAndClassID(eContainer EClass, classID int) EOperation
	CreateEPackage() EPackage
	CreateEPackageFromContainer(eContainer EPackage) EPackage
	CreateEParameter() EParameter
	CreateEParameterFromContainer(eContainer EOperation) EParameter
	CreateEReference() EReference
	CreateEReferenceFromContainer(eContainer EClass) EReference
	CreateEReferenceFromContainerAndClassID(eContainer EClass, classID int) EReference
	CreateEStringToStringMapEntry() EStringToStringMapEntry
	CreateETypeParameter() ETypeParameter
}

var factoryInstance EcoreFactory

// GetFactory returns the factory for the model ecore
func GetFactory() EcoreFactory {
	if factoryInstance == nil {
		factoryInstance = newEcoreFactoryImpl()
	}
	return factoryInstance
}
