// Code generated by soft.generator.go. DO NOT EDIT.

// *****************************************************************************
// Copyright(c) 2021 MASA Group
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// *****************************************************************************

package ecore

// ecorePackageImpl is the EcorePackage implementation
type ecorePackageImpl struct {
	EPackageExt
	eAnnotation             EClass
	eAttribute              EClass
	eClass                  EClass
	eClassifier             EClass
	eDataType               EClass
	eEnum                   EClass
	eEnumLiteral            EClass
	eFactory                EClass
	eGenericType            EClass
	eModelElement           EClass
	eNamedElement           EClass
	eObject                 EClass
	eOperation              EClass
	ePackage                EClass
	eParameter              EClass
	eReference              EClass
	eStringToStringMapEntry EClass
	eStructuralFeature      EClass
	eTypeParameter          EClass
	eTypedElement           EClass

	eBigDecimal                EDataType
	eBigInteger                EDataType
	eBoolean                   EDataType
	eBooleanObject             EDataType
	eByte                      EDataType
	eByteArray                 EDataType
	eByteObject                EDataType
	eChar                      EDataType
	eCharacterObject           EDataType
	eDate                      EDataType
	eDiagnosticChain           EDataType
	eDouble                    EDataType
	eDoubleObject              EDataType
	eEList                     EDataType
	eEnumerator                EDataType
	eFeatureMap                EDataType
	eFeatureMapEntry           EDataType
	eFloat                     EDataType
	eFloatObject               EDataType
	eInt                       EDataType
	eIntegerObject             EDataType
	eInvocationTargetException EDataType
	eJavaClass                 EDataType
	eJavaObject                EDataType
	eLong                      EDataType
	eLongObject                EDataType
	eMap                       EDataType
	eResource                  EDataType
	eResourceSet               EDataType
	eShort                     EDataType
	eShortObject               EDataType
	eString                    EDataType
	eTreeIterator              EDataType
}

func newEcorePackageImpl() *ecorePackageImpl {
	p := new(ecorePackageImpl)
	p.SetInterfaces(p)
	p.Initialize()
	return p
}

func (p *ecorePackageImpl) Initialize() {
	p.EPackageExt.Initialize()
	p.SetName(NAME)
	p.SetNsPrefix(NS_PREFIX)
	p.SetNsURI(NS_URI)
	p.SetEFactoryInstance(GetFactory())
	p.createPackageContents()
	p.initializePackageContents()
	p.CreateResource()
}

// GetEAnnotationClass returns the meta object corresponding to
func (p *ecorePackageImpl) GetEAnnotationClass() EClass {
	return p.eAnnotation
}

// GetEAnnotation_Source returns the meta object corresponding to
func (p *ecorePackageImpl) GetEAnnotation_Source() EAttribute {
	return p.eAnnotation.GetEStructuralFeatures().Get(0).(EAttribute)
}

// GetEAnnotation_Contents returns the meta object corresponding to
func (p *ecorePackageImpl) GetEAnnotation_Contents() EReference {
	return p.eAnnotation.GetEStructuralFeatures().Get(3).(EReference)
}

// GetEAnnotation_Details returns the meta object corresponding to
func (p *ecorePackageImpl) GetEAnnotation_Details() EReference {
	return p.eAnnotation.GetEStructuralFeatures().Get(1).(EReference)
}

// GetEAnnotation_EModelElement returns the meta object corresponding to
func (p *ecorePackageImpl) GetEAnnotation_EModelElement() EReference {
	return p.eAnnotation.GetEStructuralFeatures().Get(2).(EReference)
}

// GetEAnnotation_References returns the meta object corresponding to
func (p *ecorePackageImpl) GetEAnnotation_References() EReference {
	return p.eAnnotation.GetEStructuralFeatures().Get(4).(EReference)
}

// GetEAttribute returns the meta object corresponding to
func (p *ecorePackageImpl) GetEAttribute() EClass {
	return p.eAttribute
}

// GetEAttribute_ID returns the meta object corresponding to
func (p *ecorePackageImpl) GetEAttribute_ID() EAttribute {
	return p.eAttribute.GetEStructuralFeatures().Get(0).(EAttribute)
}

// GetEAttribute_EAttributeType returns the meta object corresponding to
func (p *ecorePackageImpl) GetEAttribute_EAttributeType() EReference {
	return p.eAttribute.GetEStructuralFeatures().Get(1).(EReference)
}

// GetEClass returns the meta object corresponding to
func (p *ecorePackageImpl) GetEClass() EClass {
	return p.eClass
}

// GetEClass_Abstract returns the meta object corresponding to
func (p *ecorePackageImpl) GetEClass_Abstract() EAttribute {
	return p.eClass.GetEStructuralFeatures().Get(0).(EAttribute)
}

// GetEClass_Interface returns the meta object corresponding to
func (p *ecorePackageImpl) GetEClass_Interface() EAttribute {
	return p.eClass.GetEStructuralFeatures().Get(1).(EAttribute)
}

// GetEClass_EAllAttributes returns the meta object corresponding to
func (p *ecorePackageImpl) GetEClass_EAllAttributes() EReference {
	return p.eClass.GetEStructuralFeatures().Get(9).(EReference)
}

// GetEClass_EAllContainments returns the meta object corresponding to
func (p *ecorePackageImpl) GetEClass_EAllContainments() EReference {
	return p.eClass.GetEStructuralFeatures().Get(11).(EReference)
}

// GetEClass_EAllOperations returns the meta object corresponding to
func (p *ecorePackageImpl) GetEClass_EAllOperations() EReference {
	return p.eClass.GetEStructuralFeatures().Get(12).(EReference)
}

// GetEClass_EAllReferences returns the meta object corresponding to
func (p *ecorePackageImpl) GetEClass_EAllReferences() EReference {
	return p.eClass.GetEStructuralFeatures().Get(10).(EReference)
}

// GetEClass_EAllStructuralFeatures returns the meta object corresponding to
func (p *ecorePackageImpl) GetEClass_EAllStructuralFeatures() EReference {
	return p.eClass.GetEStructuralFeatures().Get(13).(EReference)
}

// GetEClass_EAllSuperTypes returns the meta object corresponding to
func (p *ecorePackageImpl) GetEClass_EAllSuperTypes() EReference {
	return p.eClass.GetEStructuralFeatures().Get(14).(EReference)
}

// GetEClass_EAttributes returns the meta object corresponding to
func (p *ecorePackageImpl) GetEClass_EAttributes() EReference {
	return p.eClass.GetEStructuralFeatures().Get(3).(EReference)
}

// GetEClass_EContainmentFeatures returns the meta object corresponding to
func (p *ecorePackageImpl) GetEClass_EContainmentFeatures() EReference {
	return p.eClass.GetEStructuralFeatures().Get(7).(EReference)
}

// GetEClass_ECrossReferenceFeatures returns the meta object corresponding to
func (p *ecorePackageImpl) GetEClass_ECrossReferenceFeatures() EReference {
	return p.eClass.GetEStructuralFeatures().Get(8).(EReference)
}

// GetEClass_EIDAttribute returns the meta object corresponding to
func (p *ecorePackageImpl) GetEClass_EIDAttribute() EReference {
	return p.eClass.GetEStructuralFeatures().Get(15).(EReference)
}

// GetEClass_EOperations returns the meta object corresponding to
func (p *ecorePackageImpl) GetEClass_EOperations() EReference {
	return p.eClass.GetEStructuralFeatures().Get(6).(EReference)
}

// GetEClass_EReferences returns the meta object corresponding to
func (p *ecorePackageImpl) GetEClass_EReferences() EReference {
	return p.eClass.GetEStructuralFeatures().Get(4).(EReference)
}

// GetEClass_EStructuralFeatures returns the meta object corresponding to
func (p *ecorePackageImpl) GetEClass_EStructuralFeatures() EReference {
	return p.eClass.GetEStructuralFeatures().Get(2).(EReference)
}

// GetEClass_ESuperTypes returns the meta object corresponding to
func (p *ecorePackageImpl) GetEClass_ESuperTypes() EReference {
	return p.eClass.GetEStructuralFeatures().Get(5).(EReference)
}

// GetEClass_GetEOperation_EInt returns the meta object corresponding to
func (p *ecorePackageImpl) GetEClass_GetEOperation_EInt() EOperation {
	return p.eClass.GetEOperations().Get(6).(EOperation)
}

// GetEClass_GetEStructuralFeature_EInt returns the meta object corresponding to
func (p *ecorePackageImpl) GetEClass_GetEStructuralFeature_EInt() EOperation {
	return p.eClass.GetEOperations().Get(2).(EOperation)
}

// GetEClass_GetEStructuralFeature_EString returns the meta object corresponding to
func (p *ecorePackageImpl) GetEClass_GetEStructuralFeature_EString() EOperation {
	return p.eClass.GetEOperations().Get(3).(EOperation)
}

// GetEClass_GetFeatureCount returns the meta object corresponding to
func (p *ecorePackageImpl) GetEClass_GetFeatureCount() EOperation {
	return p.eClass.GetEOperations().Get(1).(EOperation)
}

// GetEClass_GetFeatureID_EStructuralFeature returns the meta object corresponding to
func (p *ecorePackageImpl) GetEClass_GetFeatureID_EStructuralFeature() EOperation {
	return p.eClass.GetEOperations().Get(4).(EOperation)
}

// GetEClass_GetFeatureType_EStructuralFeature returns the meta object corresponding to
func (p *ecorePackageImpl) GetEClass_GetFeatureType_EStructuralFeature() EOperation {
	return p.eClass.GetEOperations().Get(9).(EOperation)
}

// GetEClass_GetOperationCount returns the meta object corresponding to
func (p *ecorePackageImpl) GetEClass_GetOperationCount() EOperation {
	return p.eClass.GetEOperations().Get(5).(EOperation)
}

// GetEClass_GetOperationID_EOperation returns the meta object corresponding to
func (p *ecorePackageImpl) GetEClass_GetOperationID_EOperation() EOperation {
	return p.eClass.GetEOperations().Get(7).(EOperation)
}

// GetEClass_GetOverride_EOperation returns the meta object corresponding to
func (p *ecorePackageImpl) GetEClass_GetOverride_EOperation() EOperation {
	return p.eClass.GetEOperations().Get(8).(EOperation)
}

// GetEClass_IsSuperTypeOf_EClass returns the meta object corresponding to
func (p *ecorePackageImpl) GetEClass_IsSuperTypeOf_EClass() EOperation {
	return p.eClass.GetEOperations().Get(0).(EOperation)
}

// GetEClassifierClass returns the meta object corresponding to
func (p *ecorePackageImpl) GetEClassifierClass() EClass {
	return p.eClassifier
}

// GetEClassifier_ClassifierID returns the meta object corresponding to
func (p *ecorePackageImpl) GetEClassifier_ClassifierID() EAttribute {
	return p.eClassifier.GetEStructuralFeatures().Get(5).(EAttribute)
}

// GetEClassifier_DefaultValue returns the meta object corresponding to
func (p *ecorePackageImpl) GetEClassifier_DefaultValue() EAttribute {
	return p.eClassifier.GetEStructuralFeatures().Get(3).(EAttribute)
}

// GetEClassifier_InstanceClass returns the meta object corresponding to
func (p *ecorePackageImpl) GetEClassifier_InstanceClass() EAttribute {
	return p.eClassifier.GetEStructuralFeatures().Get(1).(EAttribute)
}

// GetEClassifier_InstanceClassName returns the meta object corresponding to
func (p *ecorePackageImpl) GetEClassifier_InstanceClassName() EAttribute {
	return p.eClassifier.GetEStructuralFeatures().Get(0).(EAttribute)
}

// GetEClassifier_InstanceTypeName returns the meta object corresponding to
func (p *ecorePackageImpl) GetEClassifier_InstanceTypeName() EAttribute {
	return p.eClassifier.GetEStructuralFeatures().Get(2).(EAttribute)
}

// GetEClassifier_EPackage returns the meta object corresponding to
func (p *ecorePackageImpl) GetEClassifier_EPackage() EReference {
	return p.eClassifier.GetEStructuralFeatures().Get(4).(EReference)
}

// GetEClassifier_IsInstance_EJavaObject returns the meta object corresponding to
func (p *ecorePackageImpl) GetEClassifier_IsInstance_EJavaObject() EOperation {
	return p.eClassifier.GetEOperations().Get(0).(EOperation)
}

// GetEDataType returns the meta object corresponding to
func (p *ecorePackageImpl) GetEDataType() EClass {
	return p.eDataType
}

// GetEDataType_Serializable returns the meta object corresponding to
func (p *ecorePackageImpl) GetEDataType_Serializable() EAttribute {
	return p.eDataType.GetEStructuralFeatures().Get(0).(EAttribute)
}

// GetEEnum returns the meta object corresponding to
func (p *ecorePackageImpl) GetEEnum() EClass {
	return p.eEnum
}

// GetEEnum_ELiterals returns the meta object corresponding to
func (p *ecorePackageImpl) GetEEnum_ELiterals() EReference {
	return p.eEnum.GetEStructuralFeatures().Get(0).(EReference)
}

// GetEEnum_GetEEnumLiteral_EString returns the meta object corresponding to
func (p *ecorePackageImpl) GetEEnum_GetEEnumLiteral_EString() EOperation {
	return p.eEnum.GetEOperations().Get(0).(EOperation)
}

// GetEEnum_GetEEnumLiteral_EInt returns the meta object corresponding to
func (p *ecorePackageImpl) GetEEnum_GetEEnumLiteral_EInt() EOperation {
	return p.eEnum.GetEOperations().Get(1).(EOperation)
}

// GetEEnum_GetEEnumLiteralByLiteral_EString returns the meta object corresponding to
func (p *ecorePackageImpl) GetEEnum_GetEEnumLiteralByLiteral_EString() EOperation {
	return p.eEnum.GetEOperations().Get(2).(EOperation)
}

// GetEEnumLiteral returns the meta object corresponding to
func (p *ecorePackageImpl) GetEEnumLiteral() EClass {
	return p.eEnumLiteral
}

// GetEEnumLiteral_Instance returns the meta object corresponding to
func (p *ecorePackageImpl) GetEEnumLiteral_Instance() EAttribute {
	return p.eEnumLiteral.GetEStructuralFeatures().Get(1).(EAttribute)
}

// GetEEnumLiteral_Literal returns the meta object corresponding to
func (p *ecorePackageImpl) GetEEnumLiteral_Literal() EAttribute {
	return p.eEnumLiteral.GetEStructuralFeatures().Get(2).(EAttribute)
}

// GetEEnumLiteral_Value returns the meta object corresponding to
func (p *ecorePackageImpl) GetEEnumLiteral_Value() EAttribute {
	return p.eEnumLiteral.GetEStructuralFeatures().Get(0).(EAttribute)
}

// GetEEnumLiteral_EEnum returns the meta object corresponding to
func (p *ecorePackageImpl) GetEEnumLiteral_EEnum() EReference {
	return p.eEnumLiteral.GetEStructuralFeatures().Get(3).(EReference)
}

// GetEFactory returns the meta object corresponding to
func (p *ecorePackageImpl) GetEFactory() EClass {
	return p.eFactory
}

// GetEFactory_EPackage returns the meta object corresponding to
func (p *ecorePackageImpl) GetEFactory_EPackage() EReference {
	return p.eFactory.GetEStructuralFeatures().Get(0).(EReference)
}

// GetEFactory_ConvertToString_EDataType_EJavaObject returns the meta object corresponding to
func (p *ecorePackageImpl) GetEFactory_ConvertToString_EDataType_EJavaObject() EOperation {
	return p.eFactory.GetEOperations().Get(2).(EOperation)
}

// GetEFactory_Create_EClass returns the meta object corresponding to
func (p *ecorePackageImpl) GetEFactory_Create_EClass() EOperation {
	return p.eFactory.GetEOperations().Get(0).(EOperation)
}

// GetEFactory_CreateFromString_EDataType_EString returns the meta object corresponding to
func (p *ecorePackageImpl) GetEFactory_CreateFromString_EDataType_EString() EOperation {
	return p.eFactory.GetEOperations().Get(1).(EOperation)
}

// GetEGenericType returns the meta object corresponding to
func (p *ecorePackageImpl) GetEGenericType() EClass {
	return p.eGenericType
}

// GetEGenericType_EClassifier returns the meta object corresponding to
func (p *ecorePackageImpl) GetEGenericType_EClassifier() EReference {
	return p.eGenericType.GetEStructuralFeatures().Get(5).(EReference)
}

// GetEGenericType_ELowerBound returns the meta object corresponding to
func (p *ecorePackageImpl) GetEGenericType_ELowerBound() EReference {
	return p.eGenericType.GetEStructuralFeatures().Get(3).(EReference)
}

// GetEGenericType_ERawType returns the meta object corresponding to
func (p *ecorePackageImpl) GetEGenericType_ERawType() EReference {
	return p.eGenericType.GetEStructuralFeatures().Get(2).(EReference)
}

// GetEGenericType_ETypeArguments returns the meta object corresponding to
func (p *ecorePackageImpl) GetEGenericType_ETypeArguments() EReference {
	return p.eGenericType.GetEStructuralFeatures().Get(1).(EReference)
}

// GetEGenericType_ETypeParameter returns the meta object corresponding to
func (p *ecorePackageImpl) GetEGenericType_ETypeParameter() EReference {
	return p.eGenericType.GetEStructuralFeatures().Get(4).(EReference)
}

// GetEGenericType_EUpperBound returns the meta object corresponding to
func (p *ecorePackageImpl) GetEGenericType_EUpperBound() EReference {
	return p.eGenericType.GetEStructuralFeatures().Get(0).(EReference)
}

// GetEGenericType_IsInstance_EJavaObject returns the meta object corresponding to
func (p *ecorePackageImpl) GetEGenericType_IsInstance_EJavaObject() EOperation {
	return p.eGenericType.GetEOperations().Get(0).(EOperation)
}

// GetEModelElement returns the meta object corresponding to
func (p *ecorePackageImpl) GetEModelElement() EClass {
	return p.eModelElement
}

// GetEModelElement_EAnnotations returns the meta object corresponding to
func (p *ecorePackageImpl) GetEModelElement_EAnnotations() EReference {
	return p.eModelElement.GetEStructuralFeatures().Get(0).(EReference)
}

// GetEModelElement_GetEAnnotation_EString returns the meta object corresponding to
func (p *ecorePackageImpl) GetEModelElement_GetEAnnotation_EString() EOperation {
	return p.eModelElement.GetEOperations().Get(0).(EOperation)
}

// GetENamedElement returns the meta object corresponding to
func (p *ecorePackageImpl) GetENamedElement() EClass {
	return p.eNamedElement
}

// GetENamedElement_Name returns the meta object corresponding to
func (p *ecorePackageImpl) GetENamedElement_Name() EAttribute {
	return p.eNamedElement.GetEStructuralFeatures().Get(0).(EAttribute)
}

// GetEObject returns the meta object corresponding to
func (p *ecorePackageImpl) GetEObject() EClass {
	return p.eObject
}

// GetEObject_EAllContents returns the meta object corresponding to
func (p *ecorePackageImpl) GetEObject_EAllContents() EOperation {
	return p.eObject.GetEOperations().Get(7).(EOperation)
}

// GetEObject_EClass returns the meta object corresponding to
func (p *ecorePackageImpl) GetEObject_EClass() EOperation {
	return p.eObject.GetEOperations().Get(0).(EOperation)
}

// GetEObject_EContainer returns the meta object corresponding to
func (p *ecorePackageImpl) GetEObject_EContainer() EOperation {
	return p.eObject.GetEOperations().Get(3).(EOperation)
}

// GetEObject_EContainingFeature returns the meta object corresponding to
func (p *ecorePackageImpl) GetEObject_EContainingFeature() EOperation {
	return p.eObject.GetEOperations().Get(4).(EOperation)
}

// GetEObject_EContainmentFeature returns the meta object corresponding to
func (p *ecorePackageImpl) GetEObject_EContainmentFeature() EOperation {
	return p.eObject.GetEOperations().Get(5).(EOperation)
}

// GetEObject_EContents returns the meta object corresponding to
func (p *ecorePackageImpl) GetEObject_EContents() EOperation {
	return p.eObject.GetEOperations().Get(6).(EOperation)
}

// GetEObject_ECrossReferences returns the meta object corresponding to
func (p *ecorePackageImpl) GetEObject_ECrossReferences() EOperation {
	return p.eObject.GetEOperations().Get(8).(EOperation)
}

// GetEObject_EGet_EStructuralFeature returns the meta object corresponding to
func (p *ecorePackageImpl) GetEObject_EGet_EStructuralFeature() EOperation {
	return p.eObject.GetEOperations().Get(9).(EOperation)
}

// GetEObject_EGet_EStructuralFeature_EBoolean returns the meta object corresponding to
func (p *ecorePackageImpl) GetEObject_EGet_EStructuralFeature_EBoolean() EOperation {
	return p.eObject.GetEOperations().Get(10).(EOperation)
}

// GetEObject_EInvoke_EOperation_EEList returns the meta object corresponding to
func (p *ecorePackageImpl) GetEObject_EInvoke_EOperation_EEList() EOperation {
	return p.eObject.GetEOperations().Get(14).(EOperation)
}

// GetEObject_EIsProxy returns the meta object corresponding to
func (p *ecorePackageImpl) GetEObject_EIsProxy() EOperation {
	return p.eObject.GetEOperations().Get(1).(EOperation)
}

// GetEObject_EIsSet_EStructuralFeature returns the meta object corresponding to
func (p *ecorePackageImpl) GetEObject_EIsSet_EStructuralFeature() EOperation {
	return p.eObject.GetEOperations().Get(12).(EOperation)
}

// GetEObject_EResource returns the meta object corresponding to
func (p *ecorePackageImpl) GetEObject_EResource() EOperation {
	return p.eObject.GetEOperations().Get(2).(EOperation)
}

// GetEObject_ESet_EStructuralFeature_EJavaObject returns the meta object corresponding to
func (p *ecorePackageImpl) GetEObject_ESet_EStructuralFeature_EJavaObject() EOperation {
	return p.eObject.GetEOperations().Get(11).(EOperation)
}

// GetEObject_EUnset_EStructuralFeature returns the meta object corresponding to
func (p *ecorePackageImpl) GetEObject_EUnset_EStructuralFeature() EOperation {
	return p.eObject.GetEOperations().Get(13).(EOperation)
}

// GetEOperation returns the meta object corresponding to
func (p *ecorePackageImpl) GetEOperation() EClass {
	return p.eOperation
}

// GetEOperation_OperationID returns the meta object corresponding to
func (p *ecorePackageImpl) GetEOperation_OperationID() EAttribute {
	return p.eOperation.GetEStructuralFeatures().Get(3).(EAttribute)
}

// GetEOperation_EContainingClass returns the meta object corresponding to
func (p *ecorePackageImpl) GetEOperation_EContainingClass() EReference {
	return p.eOperation.GetEStructuralFeatures().Get(0).(EReference)
}

// GetEOperation_EExceptions returns the meta object corresponding to
func (p *ecorePackageImpl) GetEOperation_EExceptions() EReference {
	return p.eOperation.GetEStructuralFeatures().Get(2).(EReference)
}

// GetEOperation_EParameters returns the meta object corresponding to
func (p *ecorePackageImpl) GetEOperation_EParameters() EReference {
	return p.eOperation.GetEStructuralFeatures().Get(1).(EReference)
}

// GetEOperation_IsOverrideOf_EOperation returns the meta object corresponding to
func (p *ecorePackageImpl) GetEOperation_IsOverrideOf_EOperation() EOperation {
	return p.eOperation.GetEOperations().Get(0).(EOperation)
}

// GetEPackage returns the meta object corresponding to
func (p *ecorePackageImpl) GetEPackage() EClass {
	return p.ePackage
}

// GetEPackage_NsPrefix returns the meta object corresponding to
func (p *ecorePackageImpl) GetEPackage_NsPrefix() EAttribute {
	return p.ePackage.GetEStructuralFeatures().Get(1).(EAttribute)
}

// GetEPackage_NsURI returns the meta object corresponding to
func (p *ecorePackageImpl) GetEPackage_NsURI() EAttribute {
	return p.ePackage.GetEStructuralFeatures().Get(0).(EAttribute)
}

// GetEPackage_EClassifiers returns the meta object corresponding to
func (p *ecorePackageImpl) GetEPackage_EClassifiers() EReference {
	return p.ePackage.GetEStructuralFeatures().Get(3).(EReference)
}

// GetEPackage_EFactoryInstance returns the meta object corresponding to
func (p *ecorePackageImpl) GetEPackage_EFactoryInstance() EReference {
	return p.ePackage.GetEStructuralFeatures().Get(2).(EReference)
}

// GetEPackage_ESubPackages returns the meta object corresponding to
func (p *ecorePackageImpl) GetEPackage_ESubPackages() EReference {
	return p.ePackage.GetEStructuralFeatures().Get(4).(EReference)
}

// GetEPackage_ESuperPackage returns the meta object corresponding to
func (p *ecorePackageImpl) GetEPackage_ESuperPackage() EReference {
	return p.ePackage.GetEStructuralFeatures().Get(5).(EReference)
}

// GetEPackage_GetEClassifier_EString returns the meta object corresponding to
func (p *ecorePackageImpl) GetEPackage_GetEClassifier_EString() EOperation {
	return p.ePackage.GetEOperations().Get(0).(EOperation)
}

// GetEParameter returns the meta object corresponding to
func (p *ecorePackageImpl) GetEParameter() EClass {
	return p.eParameter
}

// GetEParameter_EOperation returns the meta object corresponding to
func (p *ecorePackageImpl) GetEParameter_EOperation() EReference {
	return p.eParameter.GetEStructuralFeatures().Get(0).(EReference)
}

// GetEReference returns the meta object corresponding to
func (p *ecorePackageImpl) GetEReference() EClass {
	return p.eReference
}

// GetEReference_Container returns the meta object corresponding to
func (p *ecorePackageImpl) GetEReference_Container() EAttribute {
	return p.eReference.GetEStructuralFeatures().Get(1).(EAttribute)
}

// GetEReference_Containment returns the meta object corresponding to
func (p *ecorePackageImpl) GetEReference_Containment() EAttribute {
	return p.eReference.GetEStructuralFeatures().Get(0).(EAttribute)
}

// GetEReference_ResolveProxies returns the meta object corresponding to
func (p *ecorePackageImpl) GetEReference_ResolveProxies() EAttribute {
	return p.eReference.GetEStructuralFeatures().Get(2).(EAttribute)
}

// GetEReference_EKeys returns the meta object corresponding to
func (p *ecorePackageImpl) GetEReference_EKeys() EReference {
	return p.eReference.GetEStructuralFeatures().Get(5).(EReference)
}

// GetEReference_EOpposite returns the meta object corresponding to
func (p *ecorePackageImpl) GetEReference_EOpposite() EReference {
	return p.eReference.GetEStructuralFeatures().Get(3).(EReference)
}

// GetEReference_EReferenceType returns the meta object corresponding to
func (p *ecorePackageImpl) GetEReference_EReferenceType() EReference {
	return p.eReference.GetEStructuralFeatures().Get(4).(EReference)
}

// GetEStringToStringMapEntry returns the meta object corresponding to
func (p *ecorePackageImpl) GetEStringToStringMapEntry() EClass {
	return p.eStringToStringMapEntry
}

// GetEStringToStringMapEntry_Key returns the meta object corresponding to
func (p *ecorePackageImpl) GetEStringToStringMapEntry_Key() EAttribute {
	return p.eStringToStringMapEntry.GetEStructuralFeatures().Get(0).(EAttribute)
}

// GetEStringToStringMapEntry_Value returns the meta object corresponding to
func (p *ecorePackageImpl) GetEStringToStringMapEntry_Value() EAttribute {
	return p.eStringToStringMapEntry.GetEStructuralFeatures().Get(1).(EAttribute)
}

// GetEStructuralFeature returns the meta object corresponding to
func (p *ecorePackageImpl) GetEStructuralFeature() EClass {
	return p.eStructuralFeature
}

// GetEStructuralFeature_Changeable returns the meta object corresponding to
func (p *ecorePackageImpl) GetEStructuralFeature_Changeable() EAttribute {
	return p.eStructuralFeature.GetEStructuralFeatures().Get(0).(EAttribute)
}

// GetEStructuralFeature_DefaultValue returns the meta object corresponding to
func (p *ecorePackageImpl) GetEStructuralFeature_DefaultValue() EAttribute {
	return p.eStructuralFeature.GetEStructuralFeatures().Get(4).(EAttribute)
}

// GetEStructuralFeature_DefaultValueLiteral returns the meta object corresponding to
func (p *ecorePackageImpl) GetEStructuralFeature_DefaultValueLiteral() EAttribute {
	return p.eStructuralFeature.GetEStructuralFeatures().Get(3).(EAttribute)
}

// GetEStructuralFeature_Derived returns the meta object corresponding to
func (p *ecorePackageImpl) GetEStructuralFeature_Derived() EAttribute {
	return p.eStructuralFeature.GetEStructuralFeatures().Get(6).(EAttribute)
}

// GetEStructuralFeature_FeatureID returns the meta object corresponding to
func (p *ecorePackageImpl) GetEStructuralFeature_FeatureID() EAttribute {
	return p.eStructuralFeature.GetEStructuralFeatures().Get(8).(EAttribute)
}

// GetEStructuralFeature_Transient returns the meta object corresponding to
func (p *ecorePackageImpl) GetEStructuralFeature_Transient() EAttribute {
	return p.eStructuralFeature.GetEStructuralFeatures().Get(2).(EAttribute)
}

// GetEStructuralFeature_Unsettable returns the meta object corresponding to
func (p *ecorePackageImpl) GetEStructuralFeature_Unsettable() EAttribute {
	return p.eStructuralFeature.GetEStructuralFeatures().Get(5).(EAttribute)
}

// GetEStructuralFeature_Volatile returns the meta object corresponding to
func (p *ecorePackageImpl) GetEStructuralFeature_Volatile() EAttribute {
	return p.eStructuralFeature.GetEStructuralFeatures().Get(1).(EAttribute)
}

// GetEStructuralFeature_EContainingClass returns the meta object corresponding to
func (p *ecorePackageImpl) GetEStructuralFeature_EContainingClass() EReference {
	return p.eStructuralFeature.GetEStructuralFeatures().Get(7).(EReference)
}

// GetEStructuralFeature_GetContainerClass returns the meta object corresponding to
func (p *ecorePackageImpl) GetEStructuralFeature_GetContainerClass() EOperation {
	return p.eStructuralFeature.GetEOperations().Get(0).(EOperation)
}

// GetETypeParameter returns the meta object corresponding to
func (p *ecorePackageImpl) GetETypeParameter() EClass {
	return p.eTypeParameter
}

// GetETypeParameter_EBounds returns the meta object corresponding to
func (p *ecorePackageImpl) GetETypeParameter_EBounds() EReference {
	return p.eTypeParameter.GetEStructuralFeatures().Get(0).(EReference)
}

// GetETypedElement returns the meta object corresponding to
func (p *ecorePackageImpl) GetETypedElement() EClass {
	return p.eTypedElement
}

// GetETypedElement_LowerBound returns the meta object corresponding to
func (p *ecorePackageImpl) GetETypedElement_LowerBound() EAttribute {
	return p.eTypedElement.GetEStructuralFeatures().Get(2).(EAttribute)
}

// GetETypedElement_Many returns the meta object corresponding to
func (p *ecorePackageImpl) GetETypedElement_Many() EAttribute {
	return p.eTypedElement.GetEStructuralFeatures().Get(4).(EAttribute)
}

// GetETypedElement_Ordered returns the meta object corresponding to
func (p *ecorePackageImpl) GetETypedElement_Ordered() EAttribute {
	return p.eTypedElement.GetEStructuralFeatures().Get(0).(EAttribute)
}

// GetETypedElement_Required returns the meta object corresponding to
func (p *ecorePackageImpl) GetETypedElement_Required() EAttribute {
	return p.eTypedElement.GetEStructuralFeatures().Get(5).(EAttribute)
}

// GetETypedElement_Unique returns the meta object corresponding to
func (p *ecorePackageImpl) GetETypedElement_Unique() EAttribute {
	return p.eTypedElement.GetEStructuralFeatures().Get(1).(EAttribute)
}

// GetETypedElement_UpperBound returns the meta object corresponding to
func (p *ecorePackageImpl) GetETypedElement_UpperBound() EAttribute {
	return p.eTypedElement.GetEStructuralFeatures().Get(3).(EAttribute)
}

// GetETypedElement_EType returns the meta object corresponding to
func (p *ecorePackageImpl) GetETypedElement_EType() EReference {
	return p.eTypedElement.GetEStructuralFeatures().Get(6).(EReference)
}

// GetEBigDecimal returns the meta object corresponding to
func (p *ecorePackageImpl) GetEBigDecimal() EDataType {
	return p.eBigDecimal
}

// GetEBigInteger returns the meta object corresponding to
func (p *ecorePackageImpl) GetEBigInteger() EDataType {
	return p.eBigInteger
}

// GetEBoolean returns the meta object corresponding to
func (p *ecorePackageImpl) GetEBoolean() EDataType {
	return p.eBoolean
}

// GetEBooleanObject returns the meta object corresponding to
func (p *ecorePackageImpl) GetEBooleanObject() EDataType {
	return p.eBooleanObject
}

// GetEByte returns the meta object corresponding to
func (p *ecorePackageImpl) GetEByte() EDataType {
	return p.eByte
}

// GetEByteArray returns the meta object corresponding to
func (p *ecorePackageImpl) GetEByteArray() EDataType {
	return p.eByteArray
}

// GetEByteObject returns the meta object corresponding to
func (p *ecorePackageImpl) GetEByteObject() EDataType {
	return p.eByteObject
}

// GetEChar returns the meta object corresponding to
func (p *ecorePackageImpl) GetEChar() EDataType {
	return p.eChar
}

// GetECharacterObject returns the meta object corresponding to
func (p *ecorePackageImpl) GetECharacterObject() EDataType {
	return p.eCharacterObject
}

// GetEDate returns the meta object corresponding to
func (p *ecorePackageImpl) GetEDate() EDataType {
	return p.eDate
}

// GetEDiagnosticChain returns the meta object corresponding to
func (p *ecorePackageImpl) GetEDiagnosticChain() EDataType {
	return p.eDiagnosticChain
}

// GetEDouble returns the meta object corresponding to
func (p *ecorePackageImpl) GetEDouble() EDataType {
	return p.eDouble
}

// GetEDoubleObject returns the meta object corresponding to
func (p *ecorePackageImpl) GetEDoubleObject() EDataType {
	return p.eDoubleObject
}

// GetEEList returns the meta object corresponding to
func (p *ecorePackageImpl) GetEEList() EDataType {
	return p.eEList
}

// GetEEnumerator returns the meta object corresponding to
func (p *ecorePackageImpl) GetEEnumerator() EDataType {
	return p.eEnumerator
}

// GetEFeatureMap returns the meta object corresponding to
func (p *ecorePackageImpl) GetEFeatureMap() EDataType {
	return p.eFeatureMap
}

// GetEFeatureMapEntry returns the meta object corresponding to
func (p *ecorePackageImpl) GetEFeatureMapEntry() EDataType {
	return p.eFeatureMapEntry
}

// GetEFloat returns the meta object corresponding to
func (p *ecorePackageImpl) GetEFloat() EDataType {
	return p.eFloat
}

// GetEFloatObject returns the meta object corresponding to
func (p *ecorePackageImpl) GetEFloatObject() EDataType {
	return p.eFloatObject
}

// GetEInt returns the meta object corresponding to
func (p *ecorePackageImpl) GetEInt() EDataType {
	return p.eInt
}

// GetEIntegerObject returns the meta object corresponding to
func (p *ecorePackageImpl) GetEIntegerObject() EDataType {
	return p.eIntegerObject
}

// GetEInvocationTargetException returns the meta object corresponding to
func (p *ecorePackageImpl) GetEInvocationTargetException() EDataType {
	return p.eInvocationTargetException
}

// GetEJavaClass returns the meta object corresponding to
func (p *ecorePackageImpl) GetEJavaClass() EDataType {
	return p.eJavaClass
}

// GetEJavaObject returns the meta object corresponding to
func (p *ecorePackageImpl) GetEJavaObject() EDataType {
	return p.eJavaObject
}

// GetELong returns the meta object corresponding to
func (p *ecorePackageImpl) GetELong() EDataType {
	return p.eLong
}

// GetELongObject returns the meta object corresponding to
func (p *ecorePackageImpl) GetELongObject() EDataType {
	return p.eLongObject
}

// GetEMap returns the meta object corresponding to
func (p *ecorePackageImpl) GetEMap() EDataType {
	return p.eMap
}

// GetEResource returns the meta object corresponding to
func (p *ecorePackageImpl) GetEResource() EDataType {
	return p.eResource
}

// GetEResourceSet returns the meta object corresponding to
func (p *ecorePackageImpl) GetEResourceSet() EDataType {
	return p.eResourceSet
}

// GetEShort returns the meta object corresponding to
func (p *ecorePackageImpl) GetEShort() EDataType {
	return p.eShort
}

// GetEShortObject returns the meta object corresponding to
func (p *ecorePackageImpl) GetEShortObject() EDataType {
	return p.eShortObject
}

// GetEString returns the meta object corresponding to
func (p *ecorePackageImpl) GetEString() EDataType {
	return p.eString
}

// GetETreeIterator returns the meta object corresponding to
func (p *ecorePackageImpl) GetETreeIterator() EDataType {
	return p.eTreeIterator
}

func (p *ecorePackageImpl) createPackageContents() {
	factory := GetFactory()

	p.eAnnotation = factory.CreateEClassFromContainerAndClassID(p, EANNOTATION)
	factory.CreateEAttributeFromContainerAndClassID(p.eAnnotation, EANNOTATION__SOURCE)
	factory.CreateEReferenceFromContainerAndClassID(p.eAnnotation, EANNOTATION__DETAILS)
	factory.CreateEReferenceFromContainerAndClassID(p.eAnnotation, EANNOTATION__EMODEL_ELEMENT)
	factory.CreateEReferenceFromContainerAndClassID(p.eAnnotation, EANNOTATION__CONTENTS)
	factory.CreateEReferenceFromContainerAndClassID(p.eAnnotation, EANNOTATION__REFERENCES)

	p.eAttribute = factory.CreateEClassFromContainerAndClassID(p, EATTRIBUTE)
	factory.CreateEAttributeFromContainerAndClassID(p.eAttribute, EATTRIBUTE__ID)
	factory.CreateEReferenceFromContainerAndClassID(p.eAttribute, EATTRIBUTE__EATTRIBUTE_TYPE)

	p.eClass = factory.CreateEClassFromContainerAndClassID(p, ECLASS)
	factory.CreateEAttributeFromContainerAndClassID(p.eClass, ECLASS__ABSTRACT)
	factory.CreateEAttributeFromContainerAndClassID(p.eClass, ECLASS__INTERFACE)
	factory.CreateEReferenceFromContainerAndClassID(p.eClass, ECLASS__ESTRUCTURAL_FEATURES)
	factory.CreateEReferenceFromContainerAndClassID(p.eClass, ECLASS__EATTRIBUTES)
	factory.CreateEReferenceFromContainerAndClassID(p.eClass, ECLASS__EREFERENCES)
	factory.CreateEReferenceFromContainerAndClassID(p.eClass, ECLASS__ESUPER_TYPES)
	factory.CreateEReferenceFromContainerAndClassID(p.eClass, ECLASS__EOPERATIONS)
	factory.CreateEReferenceFromContainerAndClassID(p.eClass, ECLASS__ECONTAINMENT_FEATURES)
	factory.CreateEReferenceFromContainerAndClassID(p.eClass, ECLASS__ECROSS_REFERENCE_FEATURES)
	factory.CreateEReferenceFromContainerAndClassID(p.eClass, ECLASS__EALL_ATTRIBUTES)
	factory.CreateEReferenceFromContainerAndClassID(p.eClass, ECLASS__EALL_REFERENCES)
	factory.CreateEReferenceFromContainerAndClassID(p.eClass, ECLASS__EALL_CONTAINMENTS)
	factory.CreateEReferenceFromContainerAndClassID(p.eClass, ECLASS__EALL_OPERATIONS)
	factory.CreateEReferenceFromContainerAndClassID(p.eClass, ECLASS__EALL_STRUCTURAL_FEATURES)
	factory.CreateEReferenceFromContainerAndClassID(p.eClass, ECLASS__EALL_SUPER_TYPES)
	factory.CreateEReferenceFromContainerAndClassID(p.eClass, ECLASS__EID_ATTRIBUTE)
	factory.CreateEOperationFromContainerAndClassID(p.eClass, ECLASS__IS_SUPER_TYPE_OF_ECLASS)
	factory.CreateEOperationFromContainerAndClassID(p.eClass, ECLASS__GET_FEATURE_COUNT)
	factory.CreateEOperationFromContainerAndClassID(p.eClass, ECLASS__GET_ESTRUCTURAL_FEATURE_EINT)
	factory.CreateEOperationFromContainerAndClassID(p.eClass, ECLASS__GET_ESTRUCTURAL_FEATURE_ESTRING)
	factory.CreateEOperationFromContainerAndClassID(p.eClass, ECLASS__GET_FEATURE_ID_ESTRUCTURALFEATURE)
	factory.CreateEOperationFromContainerAndClassID(p.eClass, ECLASS__GET_OPERATION_COUNT)
	factory.CreateEOperationFromContainerAndClassID(p.eClass, ECLASS__GET_EOPERATION_EINT)
	factory.CreateEOperationFromContainerAndClassID(p.eClass, ECLASS__GET_OPERATION_ID_EOPERATION)
	factory.CreateEOperationFromContainerAndClassID(p.eClass, ECLASS__GET_OVERRIDE_EOPERATION)
	factory.CreateEOperationFromContainerAndClassID(p.eClass, ECLASS__GET_FEATURE_TYPE_ESTRUCTURALFEATURE)

	p.eClassifier = factory.CreateEClassFromContainerAndClassID(p, ECLASSIFIER)
	factory.CreateEAttributeFromContainerAndClassID(p.eClassifier, ECLASSIFIER__INSTANCE_CLASS_NAME)
	factory.CreateEAttributeFromContainerAndClassID(p.eClassifier, ECLASSIFIER__INSTANCE_CLASS)
	factory.CreateEAttributeFromContainerAndClassID(p.eClassifier, ECLASSIFIER__INSTANCE_TYPE_NAME)
	factory.CreateEAttributeFromContainerAndClassID(p.eClassifier, ECLASSIFIER__DEFAULT_VALUE)
	factory.CreateEReferenceFromContainerAndClassID(p.eClassifier, ECLASSIFIER__EPACKAGE)
	factory.CreateEAttributeFromContainerAndClassID(p.eClassifier, ECLASSIFIER__CLASSIFIER_ID)
	factory.CreateEOperationFromContainerAndClassID(p.eClassifier, ECLASSIFIER__IS_INSTANCE_EJAVAOBJECT)

	p.eDataType = factory.CreateEClassFromContainerAndClassID(p, EDATA_TYPE)
	factory.CreateEAttributeFromContainerAndClassID(p.eDataType, EDATA_TYPE__SERIALIZABLE)

	p.eEnum = factory.CreateEClassFromContainerAndClassID(p, EENUM)
	factory.CreateEReferenceFromContainerAndClassID(p.eEnum, EENUM__ELITERALS)
	factory.CreateEOperationFromContainerAndClassID(p.eEnum, EENUM__GET_EENUM_LITERAL_ESTRING)
	factory.CreateEOperationFromContainerAndClassID(p.eEnum, EENUM__GET_EENUM_LITERAL_EINT)
	factory.CreateEOperationFromContainerAndClassID(p.eEnum, EENUM__GET_EENUM_LITERAL_BY_LITERAL_ESTRING)

	p.eEnumLiteral = factory.CreateEClassFromContainerAndClassID(p, EENUM_LITERAL)
	factory.CreateEAttributeFromContainerAndClassID(p.eEnumLiteral, EENUM_LITERAL__VALUE)
	factory.CreateEAttributeFromContainerAndClassID(p.eEnumLiteral, EENUM_LITERAL__INSTANCE)
	factory.CreateEAttributeFromContainerAndClassID(p.eEnumLiteral, EENUM_LITERAL__LITERAL)
	factory.CreateEReferenceFromContainerAndClassID(p.eEnumLiteral, EENUM_LITERAL__EENUM)

	p.eFactory = factory.CreateEClassFromContainerAndClassID(p, EFACTORY)
	factory.CreateEReferenceFromContainerAndClassID(p.eFactory, EFACTORY__EPACKAGE)
	factory.CreateEOperationFromContainerAndClassID(p.eFactory, EFACTORY__CREATE_ECLASS)
	factory.CreateEOperationFromContainerAndClassID(p.eFactory, EFACTORY__CREATE_FROM_STRING_EDATATYPE_ESTRING)
	factory.CreateEOperationFromContainerAndClassID(p.eFactory, EFACTORY__CONVERT_TO_STRING_EDATATYPE_EJAVAOBJECT)

	p.eGenericType = factory.CreateEClassFromContainerAndClassID(p, EGENERIC_TYPE)
	factory.CreateEReferenceFromContainerAndClassID(p.eGenericType, EGENERIC_TYPE__EUPPER_BOUND)
	factory.CreateEReferenceFromContainerAndClassID(p.eGenericType, EGENERIC_TYPE__ETYPE_ARGUMENTS)
	factory.CreateEReferenceFromContainerAndClassID(p.eGenericType, EGENERIC_TYPE__ERAW_TYPE)
	factory.CreateEReferenceFromContainerAndClassID(p.eGenericType, EGENERIC_TYPE__ELOWER_BOUND)
	factory.CreateEReferenceFromContainerAndClassID(p.eGenericType, EGENERIC_TYPE__ETYPE_PARAMETER)
	factory.CreateEReferenceFromContainerAndClassID(p.eGenericType, EGENERIC_TYPE__ECLASSIFIER)
	factory.CreateEOperationFromContainerAndClassID(p.eGenericType, EGENERIC_TYPE__IS_INSTANCE_EJAVAOBJECT)

	p.eModelElement = factory.CreateEClassFromContainerAndClassID(p, EMODEL_ELEMENT)
	factory.CreateEReferenceFromContainerAndClassID(p.eModelElement, EMODEL_ELEMENT__EANNOTATIONS)
	factory.CreateEOperationFromContainerAndClassID(p.eModelElement, EMODEL_ELEMENT__GET_EANNOTATION_ESTRING)

	p.eNamedElement = factory.CreateEClassFromContainerAndClassID(p, ENAMED_ELEMENT)
	factory.CreateEAttributeFromContainerAndClassID(p.eNamedElement, ENAMED_ELEMENT__NAME)

	p.eObject = factory.CreateEClassFromContainerAndClassID(p, EOBJECT)
	factory.CreateEOperationFromContainerAndClassID(p.eObject, EOBJECT__ECLASS)
	factory.CreateEOperationFromContainerAndClassID(p.eObject, EOBJECT__EIS_PROXY)
	factory.CreateEOperationFromContainerAndClassID(p.eObject, EOBJECT__ERESOURCE)
	factory.CreateEOperationFromContainerAndClassID(p.eObject, EOBJECT__ECONTAINER)
	factory.CreateEOperationFromContainerAndClassID(p.eObject, EOBJECT__ECONTAINING_FEATURE)
	factory.CreateEOperationFromContainerAndClassID(p.eObject, EOBJECT__ECONTAINMENT_FEATURE)
	factory.CreateEOperationFromContainerAndClassID(p.eObject, EOBJECT__ECONTENTS)
	factory.CreateEOperationFromContainerAndClassID(p.eObject, EOBJECT__EALL_CONTENTS)
	factory.CreateEOperationFromContainerAndClassID(p.eObject, EOBJECT__ECROSS_REFERENCES)
	factory.CreateEOperationFromContainerAndClassID(p.eObject, EOBJECT__EGET_ESTRUCTURALFEATURE)
	factory.CreateEOperationFromContainerAndClassID(p.eObject, EOBJECT__EGET_ESTRUCTURALFEATURE_EBOOLEAN)
	factory.CreateEOperationFromContainerAndClassID(p.eObject, EOBJECT__ESET_ESTRUCTURALFEATURE_EJAVAOBJECT)
	factory.CreateEOperationFromContainerAndClassID(p.eObject, EOBJECT__EIS_SET_ESTRUCTURALFEATURE)
	factory.CreateEOperationFromContainerAndClassID(p.eObject, EOBJECT__EUNSET_ESTRUCTURALFEATURE)
	factory.CreateEOperationFromContainerAndClassID(p.eObject, EOBJECT__EINVOKE_EOPERATION_EELIST)

	p.eOperation = factory.CreateEClassFromContainerAndClassID(p, EOPERATION)
	factory.CreateEReferenceFromContainerAndClassID(p.eOperation, EOPERATION__ECONTAINING_CLASS)
	factory.CreateEReferenceFromContainerAndClassID(p.eOperation, EOPERATION__EPARAMETERS)
	factory.CreateEReferenceFromContainerAndClassID(p.eOperation, EOPERATION__EEXCEPTIONS)
	factory.CreateEAttributeFromContainerAndClassID(p.eOperation, EOPERATION__OPERATION_ID)
	factory.CreateEOperationFromContainerAndClassID(p.eOperation, EOPERATION__IS_OVERRIDE_OF_EOPERATION)

	p.ePackage = factory.CreateEClassFromContainerAndClassID(p, EPACKAGE)
	factory.CreateEAttributeFromContainerAndClassID(p.ePackage, EPACKAGE__NS_URI)
	factory.CreateEAttributeFromContainerAndClassID(p.ePackage, EPACKAGE__NS_PREFIX)
	factory.CreateEReferenceFromContainerAndClassID(p.ePackage, EPACKAGE__EFACTORY_INSTANCE)
	factory.CreateEReferenceFromContainerAndClassID(p.ePackage, EPACKAGE__ECLASSIFIERS)
	factory.CreateEReferenceFromContainerAndClassID(p.ePackage, EPACKAGE__ESUB_PACKAGES)
	factory.CreateEReferenceFromContainerAndClassID(p.ePackage, EPACKAGE__ESUPER_PACKAGE)
	factory.CreateEOperationFromContainerAndClassID(p.ePackage, EPACKAGE__GET_ECLASSIFIER_ESTRING)

	p.eParameter = factory.CreateEClassFromContainerAndClassID(p, EPARAMETER)
	factory.CreateEReferenceFromContainerAndClassID(p.eParameter, EPARAMETER__EOPERATION)

	p.eReference = factory.CreateEClassFromContainerAndClassID(p, EREFERENCE)
	factory.CreateEAttributeFromContainerAndClassID(p.eReference, EREFERENCE__CONTAINMENT)
	factory.CreateEAttributeFromContainerAndClassID(p.eReference, EREFERENCE__CONTAINER)
	factory.CreateEAttributeFromContainerAndClassID(p.eReference, EREFERENCE__RESOLVE_PROXIES)
	factory.CreateEReferenceFromContainerAndClassID(p.eReference, EREFERENCE__EOPPOSITE)
	factory.CreateEReferenceFromContainerAndClassID(p.eReference, EREFERENCE__EREFERENCE_TYPE)
	factory.CreateEReferenceFromContainerAndClassID(p.eReference, EREFERENCE__EKEYS)

	p.eStringToStringMapEntry = factory.CreateEClassFromContainerAndClassID(p, ESTRING_TO_STRING_MAP_ENTRY)
	factory.CreateEAttributeFromContainerAndClassID(p.eStringToStringMapEntry, ESTRING_TO_STRING_MAP_ENTRY__KEY)
	factory.CreateEAttributeFromContainerAndClassID(p.eStringToStringMapEntry, ESTRING_TO_STRING_MAP_ENTRY__VALUE)

	p.eStructuralFeature = factory.CreateEClassFromContainerAndClassID(p, ESTRUCTURAL_FEATURE)
	factory.CreateEAttributeFromContainerAndClassID(p.eStructuralFeature, ESTRUCTURAL_FEATURE__CHANGEABLE)
	factory.CreateEAttributeFromContainerAndClassID(p.eStructuralFeature, ESTRUCTURAL_FEATURE__VOLATILE)
	factory.CreateEAttributeFromContainerAndClassID(p.eStructuralFeature, ESTRUCTURAL_FEATURE__TRANSIENT)
	factory.CreateEAttributeFromContainerAndClassID(p.eStructuralFeature, ESTRUCTURAL_FEATURE__DEFAULT_VALUE_LITERAL)
	factory.CreateEAttributeFromContainerAndClassID(p.eStructuralFeature, ESTRUCTURAL_FEATURE__DEFAULT_VALUE)
	factory.CreateEAttributeFromContainerAndClassID(p.eStructuralFeature, ESTRUCTURAL_FEATURE__UNSETTABLE)
	factory.CreateEAttributeFromContainerAndClassID(p.eStructuralFeature, ESTRUCTURAL_FEATURE__DERIVED)
	factory.CreateEReferenceFromContainerAndClassID(p.eStructuralFeature, ESTRUCTURAL_FEATURE__ECONTAINING_CLASS)
	factory.CreateEAttributeFromContainerAndClassID(p.eStructuralFeature, ESTRUCTURAL_FEATURE__FEATURE_ID)
	factory.CreateEOperationFromContainerAndClassID(p.eStructuralFeature, ESTRUCTURAL_FEATURE__GET_CONTAINER_CLASS)

	p.eTypeParameter = factory.CreateEClassFromContainerAndClassID(p, ETYPE_PARAMETER)
	factory.CreateEReferenceFromContainerAndClassID(p.eTypeParameter, ETYPE_PARAMETER__EBOUNDS)

	p.eTypedElement = factory.CreateEClassFromContainerAndClassID(p, ETYPED_ELEMENT)
	factory.CreateEAttributeFromContainerAndClassID(p.eTypedElement, ETYPED_ELEMENT__ORDERED)
	factory.CreateEAttributeFromContainerAndClassID(p.eTypedElement, ETYPED_ELEMENT__UNIQUE)
	factory.CreateEAttributeFromContainerAndClassID(p.eTypedElement, ETYPED_ELEMENT__LOWER_BOUND)
	factory.CreateEAttributeFromContainerAndClassID(p.eTypedElement, ETYPED_ELEMENT__UPPER_BOUND)
	factory.CreateEAttributeFromContainerAndClassID(p.eTypedElement, ETYPED_ELEMENT__MANY)
	factory.CreateEAttributeFromContainerAndClassID(p.eTypedElement, ETYPED_ELEMENT__REQUIRED)
	factory.CreateEReferenceFromContainerAndClassID(p.eTypedElement, ETYPED_ELEMENT__ETYPE)

	p.eBigDecimal = factory.CreateEDataTypeFromContainerAndClassID(p, EBIG_DECIMAL)
	p.eBigInteger = factory.CreateEDataTypeFromContainerAndClassID(p, EBIG_INTEGER)
	p.eBoolean = factory.CreateEDataTypeFromContainerAndClassID(p, EBOOLEAN)
	p.eBooleanObject = factory.CreateEDataTypeFromContainerAndClassID(p, EBOOLEAN_OBJECT)
	p.eByte = factory.CreateEDataTypeFromContainerAndClassID(p, EBYTE)
	p.eByteArray = factory.CreateEDataTypeFromContainerAndClassID(p, EBYTE_ARRAY)
	p.eByteObject = factory.CreateEDataTypeFromContainerAndClassID(p, EBYTE_OBJECT)
	p.eChar = factory.CreateEDataTypeFromContainerAndClassID(p, ECHAR)
	p.eCharacterObject = factory.CreateEDataTypeFromContainerAndClassID(p, ECHARACTER_OBJECT)
	p.eDate = factory.CreateEDataTypeFromContainerAndClassID(p, EDATE)
	p.eDiagnosticChain = factory.CreateEDataTypeFromContainerAndClassID(p, EDIAGNOSTIC_CHAIN)
	p.eDouble = factory.CreateEDataTypeFromContainerAndClassID(p, EDOUBLE)
	p.eDoubleObject = factory.CreateEDataTypeFromContainerAndClassID(p, EDOUBLE_OBJECT)
	p.eEList = factory.CreateEDataTypeFromContainerAndClassID(p, EE_LIST)
	p.eEnumerator = factory.CreateEDataTypeFromContainerAndClassID(p, EENUMERATOR)
	p.eFeatureMap = factory.CreateEDataTypeFromContainerAndClassID(p, EFEATURE_MAP)
	p.eFeatureMapEntry = factory.CreateEDataTypeFromContainerAndClassID(p, EFEATURE_MAP_ENTRY)
	p.eFloat = factory.CreateEDataTypeFromContainerAndClassID(p, EFLOAT)
	p.eFloatObject = factory.CreateEDataTypeFromContainerAndClassID(p, EFLOAT_OBJECT)
	p.eInt = factory.CreateEDataTypeFromContainerAndClassID(p, EINT)
	p.eIntegerObject = factory.CreateEDataTypeFromContainerAndClassID(p, EINTEGER_OBJECT)
	p.eInvocationTargetException = factory.CreateEDataTypeFromContainerAndClassID(p, EINVOCATION_TARGET_EXCEPTION)
	p.eJavaClass = factory.CreateEDataTypeFromContainerAndClassID(p, EJAVA_CLASS)
	p.eJavaObject = factory.CreateEDataTypeFromContainerAndClassID(p, EJAVA_OBJECT)
	p.eLong = factory.CreateEDataTypeFromContainerAndClassID(p, ELONG)
	p.eLongObject = factory.CreateEDataTypeFromContainerAndClassID(p, ELONG_OBJECT)
	p.eMap = factory.CreateEDataTypeFromContainerAndClassID(p, EMAP)
	p.eResource = factory.CreateEDataTypeFromContainerAndClassID(p, ERESOURCE)
	p.eResourceSet = factory.CreateEDataTypeFromContainerAndClassID(p, ERESOURCE_SET)
	p.eShort = factory.CreateEDataTypeFromContainerAndClassID(p, ESHORT)
	p.eShortObject = factory.CreateEDataTypeFromContainerAndClassID(p, ESHORT_OBJECT)
	p.eString = factory.CreateEDataTypeFromContainerAndClassID(p, ESTRING)
	p.eTreeIterator = factory.CreateEDataTypeFromContainerAndClassID(p, ETREE_ITERATOR)

}

func (p *ecorePackageImpl) initializePackageContents() {

	p.eAnnotation.GetESuperTypes().Add(p.GetEModelElement())
	p.eAttribute.GetESuperTypes().Add(p.GetEStructuralFeature())
	p.eClass.GetESuperTypes().Add(p.GetEClassifierClass())
	p.eClassifier.GetESuperTypes().Add(p.GetENamedElement())
	p.eDataType.GetESuperTypes().Add(p.GetEClassifierClass())
	p.eEnum.GetESuperTypes().Add(p.GetEDataType())
	p.eEnumLiteral.GetESuperTypes().Add(p.GetENamedElement())
	p.eFactory.GetESuperTypes().Add(p.GetEModelElement())
	p.eNamedElement.GetESuperTypes().Add(p.GetEModelElement())
	p.eOperation.GetESuperTypes().Add(p.GetETypedElement())
	p.ePackage.GetESuperTypes().Add(p.GetENamedElement())
	p.eParameter.GetESuperTypes().Add(p.GetETypedElement())
	p.eReference.GetESuperTypes().Add(p.GetEStructuralFeature())
	p.eStructuralFeature.GetESuperTypes().Add(p.GetETypedElement())
	p.eTypeParameter.GetESuperTypes().Add(p.GetENamedElement())
	p.eTypedElement.GetESuperTypes().Add(p.GetENamedElement())

	p.InitEClass(p.eAnnotation, "EAnnotation", "ecore.EAnnotation", false, false)
	p.InitEAttribute(p.GetEAnnotation_Source(), p.GetEString(), "source", "", 0, 1, false, false, true, false, true, false, true, false)
	p.InitEReference(p.GetEAnnotation_Details(), p.GetEStringToStringMapEntry(), nil, "details", "", 0, -1, false, false, true, true, false, false, true, false, true)
	p.InitEReference(p.GetEAnnotation_EModelElement(), p.GetEModelElement(), p.GetEModelElement_EAnnotations(), "eModelElement", "", 0, 1, true, false, true, false, false, false, true, false, true)
	p.InitEReference(p.GetEAnnotation_Contents(), p.GetEObject(), nil, "contents", "", 0, -1, false, false, true, true, false, false, true, false, true)
	p.InitEReference(p.GetEAnnotation_References(), p.GetEObject(), nil, "references", "", 0, -1, false, false, true, false, true, false, true, false, true)

	p.InitEClass(p.eAttribute, "EAttribute", "ecore.EAttribute", false, false)
	p.InitEAttribute(p.GetEAttribute_ID(), p.GetEBoolean(), "iD", "", 0, 1, false, false, true, false, true, false, true, false)
	p.InitEReference(p.GetEAttribute_EAttributeType(), p.GetEDataType(), nil, "eAttributeType", "", 1, 1, true, true, false, false, true, false, true, true, true)

	p.InitEClass(p.eClass, "EClass", "ecore.EClass", false, false)
	p.InitEAttribute(p.GetEClass_Abstract(), p.GetEBoolean(), "abstract", "", 0, 1, false, false, true, false, true, false, true, false)
	p.InitEAttribute(p.GetEClass_Interface(), p.GetEBoolean(), "interface", "", 0, 1, false, false, true, false, true, false, true, false)
	p.InitEReference(p.GetEClass_EStructuralFeatures(), p.GetEStructuralFeature(), p.GetEStructuralFeature_EContainingClass(), "eStructuralFeatures", "", 0, -1, false, false, true, true, false, false, true, false, true)
	p.InitEReference(p.GetEClass_EAttributes(), p.GetEAttribute(), nil, "eAttributes", "", 0, -1, true, false, false, false, true, false, true, true, true)
	p.InitEReference(p.GetEClass_EReferences(), p.GetEReference(), nil, "eReferences", "", 0, -1, true, false, false, false, true, false, true, true, true)
	p.InitEReference(p.GetEClass_ESuperTypes(), p.GetEClass(), nil, "eSuperTypes", "", 0, -1, false, false, true, false, true, false, true, false, true)
	p.InitEReference(p.GetEClass_EOperations(), p.GetEOperation(), p.GetEOperation_EContainingClass(), "eOperations", "", 0, -1, false, false, true, true, false, false, true, false, true)
	p.InitEReference(p.GetEClass_EContainmentFeatures(), p.GetEStructuralFeature(), nil, "eContainmentFeatures", "", 0, -1, true, false, false, false, true, false, true, true, true)
	p.InitEReference(p.GetEClass_ECrossReferenceFeatures(), p.GetEStructuralFeature(), nil, "eCrossReferenceFeatures", "", 0, -1, true, false, false, false, true, false, true, true, true)
	p.InitEReference(p.GetEClass_EAllAttributes(), p.GetEAttribute(), nil, "eAllAttributes", "", 0, -1, true, false, false, false, true, false, true, true, true)
	p.InitEReference(p.GetEClass_EAllReferences(), p.GetEReference(), nil, "eAllReferences", "", 0, -1, true, false, false, false, true, false, true, true, true)
	p.InitEReference(p.GetEClass_EAllContainments(), p.GetEReference(), nil, "eAllContainments", "", 0, -1, true, false, false, false, true, false, true, true, true)
	p.InitEReference(p.GetEClass_EAllOperations(), p.GetEOperation(), nil, "eAllOperations", "", 0, -1, true, false, false, false, true, false, true, true, true)
	p.InitEReference(p.GetEClass_EAllStructuralFeatures(), p.GetEStructuralFeature(), nil, "eAllStructuralFeatures", "", 0, -1, true, false, false, false, true, false, true, true, true)
	p.InitEReference(p.GetEClass_EAllSuperTypes(), p.GetEClass(), nil, "eAllSuperTypes", "", 0, -1, true, false, false, false, true, false, true, true, true)
	p.InitEReference(p.GetEClass_EIDAttribute(), p.GetEAttribute(), nil, "eIDAttribute", "", 0, 1, true, false, false, false, false, false, true, true, true)
	{
		operation := p.GetEClass_IsSuperTypeOf_EClass()
		p.InitEOperation(operation, p.GetEBoolean(), "isSuperTypeOf", 0, 1, true, true)
		p.AddEParameter(operation, p.GetEClass(), "someClass", 0, 1, true, true)
	}
	p.InitEOperation(p.GetEClass_GetFeatureCount(), p.GetEInt(), "getFeatureCount", 0, 1, true, true)
	{
		operation := p.GetEClass_GetEStructuralFeature_EInt()
		p.InitEOperation(operation, p.GetEStructuralFeature(), "getEStructuralFeature", 0, 1, true, true)
		p.AddEParameter(operation, p.GetEInt(), "featureID", 0, 1, true, true)
	}
	{
		operation := p.GetEClass_GetEStructuralFeature_EString()
		p.InitEOperation(operation, p.GetEStructuralFeature(), "getEStructuralFeature", 0, 1, true, true)
		p.AddEParameter(operation, p.GetEString(), "featureName", 0, 1, true, true)
	}
	{
		operation := p.GetEClass_GetFeatureID_EStructuralFeature()
		p.InitEOperation(operation, p.GetEInt(), "getFeatureID", 0, 1, true, true)
		p.AddEParameter(operation, p.GetEStructuralFeature(), "feature", 0, 1, true, true)
	}
	p.InitEOperation(p.GetEClass_GetOperationCount(), p.GetEInt(), "getOperationCount", 0, 1, true, true)
	{
		operation := p.GetEClass_GetEOperation_EInt()
		p.InitEOperation(operation, p.GetEOperation(), "getEOperation", 0, 1, true, true)
		p.AddEParameter(operation, p.GetEInt(), "operationID", 0, 1, true, true)
	}
	{
		operation := p.GetEClass_GetOperationID_EOperation()
		p.InitEOperation(operation, p.GetEInt(), "getOperationID", 0, 1, true, true)
		p.AddEParameter(operation, p.GetEOperation(), "operation", 0, 1, true, true)
	}
	{
		operation := p.GetEClass_GetOverride_EOperation()
		p.InitEOperation(operation, p.GetEOperation(), "getOverride", 0, 1, true, true)
		p.AddEParameter(operation, p.GetEOperation(), "operation", 0, 1, true, true)
	}
	{
		operation := p.GetEClass_GetFeatureType_EStructuralFeature()
		p.InitEOperation(operation, p.GetEClassifierClass(), "getFeatureType", 0, 1, true, true)
		p.AddEParameter(operation, p.GetEStructuralFeature(), "feature", 0, 1, true, true)
	}

	p.InitEClass(p.eClassifier, "EClassifier", "ecore.EClassifier", true, false)
	p.InitEAttribute(p.GetEClassifier_InstanceClassName(), p.GetEString(), "instanceClassName", "", 0, 1, false, false, true, false, true, false, true, false)
	p.InitEAttribute(p.GetEClassifier_InstanceClass(), p.GetEJavaClass(), "instanceClass", "", 0, 1, false, false, true, false, true, false, true, false)
	p.InitEAttribute(p.GetEClassifier_InstanceTypeName(), p.GetEString(), "instanceTypeName", "", 0, 1, false, true, true, false, true, false, true, false)
	p.InitEAttribute(p.GetEClassifier_DefaultValue(), p.GetEJavaObject(), "defaultValue", "", 0, 1, true, true, false, false, true, true, true, false)
	p.InitEAttribute(p.GetEClassifier_ClassifierID(), p.GetEInt(), "classifierID", "-1", 0, 1, true, false, true, false, true, false, true, false)
	p.InitEReference(p.GetEClassifier_EPackage(), p.GetEPackage(), p.GetEPackage_EClassifiers(), "ePackage", "", 0, 1, true, false, false, false, true, false, true, false, true)
	{
		operation := p.GetEClassifier_IsInstance_EJavaObject()
		p.InitEOperation(operation, p.GetEBoolean(), "isInstance", 0, 1, true, true)
		p.AddEParameter(operation, p.GetEJavaObject(), "object", 0, 1, true, true)
	}

	p.InitEClass(p.eDataType, "EDataType", "ecore.EDataType", false, false)
	p.InitEAttribute(p.GetEDataType_Serializable(), p.GetEBoolean(), "serializable", "true", 0, 1, false, false, true, false, true, false, true, false)

	p.InitEClass(p.eEnum, "EEnum", "ecore.EEnum", false, false)
	p.InitEReference(p.GetEEnum_ELiterals(), p.GetEEnumLiteral(), p.GetEEnumLiteral_EEnum(), "eLiterals", "", 0, -1, false, false, true, true, false, false, true, false, true)
	{
		operation := p.GetEEnum_GetEEnumLiteral_EString()
		p.InitEOperation(operation, p.GetEEnumLiteral(), "getEEnumLiteral", 0, 1, true, true)
		p.AddEParameter(operation, p.GetEString(), "name", 0, 1, true, true)
	}
	{
		operation := p.GetEEnum_GetEEnumLiteral_EInt()
		p.InitEOperation(operation, p.GetEEnumLiteral(), "getEEnumLiteral", 0, 1, true, true)
		p.AddEParameter(operation, p.GetEInt(), "value", 0, 1, true, true)
	}
	{
		operation := p.GetEEnum_GetEEnumLiteralByLiteral_EString()
		p.InitEOperation(operation, p.GetEEnumLiteral(), "getEEnumLiteralByLiteral", 0, 1, true, true)
		p.AddEParameter(operation, p.GetEString(), "literal", 0, 1, true, true)
	}

	p.InitEClass(p.eEnumLiteral, "EEnumLiteral", "ecore.EEnumLiteral", false, false)
	p.InitEAttribute(p.GetEEnumLiteral_Value(), p.GetEInt(), "value", "", 0, 1, false, false, true, false, true, false, true, false)
	p.InitEAttribute(p.GetEEnumLiteral_Instance(), p.GetEEnumerator(), "instance", "", 0, 1, true, false, true, false, true, false, true, false)
	p.InitEAttribute(p.GetEEnumLiteral_Literal(), p.GetEString(), "literal", "", 0, 1, false, false, true, false, true, false, true, false)
	p.InitEReference(p.GetEEnumLiteral_EEnum(), p.GetEEnum(), p.GetEEnum_ELiterals(), "eEnum", "", 0, 1, true, false, false, false, false, false, true, false, true)

	p.InitEClass(p.eFactory, "EFactory", "ecore.EFactory", false, false)
	p.InitEReference(p.GetEFactory_EPackage(), p.GetEPackage(), p.GetEPackage_EFactoryInstance(), "ePackage", "", 1, 1, true, false, true, false, false, false, true, false, true)
	{
		operation := p.GetEFactory_Create_EClass()
		p.InitEOperation(operation, p.GetEObject(), "create", 0, 1, true, true)
		p.AddEParameter(operation, p.GetEClass(), "eClass", 0, 1, true, true)
	}
	{
		operation := p.GetEFactory_CreateFromString_EDataType_EString()
		p.InitEOperation(operation, p.GetEJavaObject(), "createFromString", 0, 1, true, true)
		p.AddEParameter(operation, p.GetEDataType(), "eDataType", 0, 1, true, true)
		p.AddEParameter(operation, p.GetEString(), "literalValue", 0, 1, true, true)
	}
	{
		operation := p.GetEFactory_ConvertToString_EDataType_EJavaObject()
		p.InitEOperation(operation, p.GetEString(), "convertToString", 0, 1, true, true)
		p.AddEParameter(operation, p.GetEDataType(), "eDataType", 0, 1, true, true)
		p.AddEParameter(operation, p.GetEJavaObject(), "instanceValue", 0, 1, true, true)
	}

	p.InitEClass(p.eGenericType, "EGenericType", "ecore.EGenericType", false, false)
	p.InitEReference(p.GetEGenericType_EUpperBound(), p.GetEGenericType(), nil, "eUpperBound", "", 0, 1, false, false, true, true, false, false, true, false, true)
	p.InitEReference(p.GetEGenericType_ETypeArguments(), p.GetEGenericType(), nil, "eTypeArguments", "", 0, -1, false, false, true, true, false, false, true, false, true)
	p.InitEReference(p.GetEGenericType_ERawType(), p.GetEClassifierClass(), nil, "eRawType", "", 1, 1, true, false, false, false, true, false, true, true, true)
	p.InitEReference(p.GetEGenericType_ELowerBound(), p.GetEGenericType(), nil, "eLowerBound", "", 0, 1, false, false, true, true, false, false, true, false, true)
	p.InitEReference(p.GetEGenericType_ETypeParameter(), p.GetETypeParameter(), nil, "eTypeParameter", "", 0, 1, false, false, true, false, false, false, true, false, true)
	p.InitEReference(p.GetEGenericType_EClassifier(), p.GetEClassifierClass(), nil, "eClassifier", "", 0, 1, false, false, true, false, true, false, true, false, true)
	{
		operation := p.GetEGenericType_IsInstance_EJavaObject()
		p.InitEOperation(operation, p.GetEBoolean(), "isInstance", 0, 1, true, true)
		p.AddEParameter(operation, p.GetEJavaObject(), "object", 0, 1, true, true)
	}

	p.InitEClass(p.eModelElement, "EModelElement", "ecore.EModelElement", true, false)
	p.InitEReference(p.GetEModelElement_EAnnotations(), p.GetEAnnotationClass(), p.GetEAnnotation_EModelElement(), "eAnnotations", "", 0, -1, false, false, true, true, false, false, true, false, true)
	{
		operation := p.GetEModelElement_GetEAnnotation_EString()
		p.InitEOperation(operation, p.GetEAnnotationClass(), "getEAnnotation", 0, 1, true, true)
		p.AddEParameter(operation, p.GetEString(), "source", 0, 1, true, true)
	}

	p.InitEClass(p.eNamedElement, "ENamedElement", "ecore.ENamedElement", true, false)
	p.InitEAttribute(p.GetENamedElement_Name(), p.GetEString(), "name", "", 0, 1, false, false, true, false, true, false, true, false)

	p.InitEClass(p.eObject, "EObject", "ecore.EObject", false, false)
	p.InitEOperation(p.GetEObject_EClass(), p.GetEClass(), "eClass", 0, 1, true, true)
	p.InitEOperation(p.GetEObject_EIsProxy(), p.GetEBoolean(), "eIsProxy", 0, 1, true, true)
	p.InitEOperation(p.GetEObject_EResource(), p.GetEResource(), "eResource", 0, 1, true, true)
	p.InitEOperation(p.GetEObject_EContainer(), p.GetEObject(), "eContainer", 0, 1, true, true)
	p.InitEOperation(p.GetEObject_EContainingFeature(), p.GetEStructuralFeature(), "eContainingFeature", 0, 1, true, true)
	p.InitEOperation(p.GetEObject_EContainmentFeature(), p.GetEReference(), "eContainmentFeature", 0, 1, true, true)
	p.InitEOperation(p.GetEObject_EContents(), p.GetEEList(), "eContents", 0, 1, true, true)
	p.InitEOperation(p.GetEObject_EAllContents(), p.GetETreeIterator(), "eAllContents", 0, 1, true, true)
	p.InitEOperation(p.GetEObject_ECrossReferences(), p.GetEEList(), "eCrossReferences", 0, 1, true, true)
	{
		operation := p.GetEObject_EGet_EStructuralFeature()
		p.InitEOperation(operation, p.GetEJavaObject(), "eGet", 0, 1, true, true)
		p.AddEParameter(operation, p.GetEStructuralFeature(), "feature", 0, 1, true, true)
	}
	{
		operation := p.GetEObject_EGet_EStructuralFeature_EBoolean()
		p.InitEOperation(operation, p.GetEJavaObject(), "eGet", 0, 1, true, true)
		p.AddEParameter(operation, p.GetEStructuralFeature(), "feature", 0, 1, true, true)
		p.AddEParameter(operation, p.GetEBoolean(), "resolve", 0, 1, true, true)
	}
	{
		operation := p.GetEObject_ESet_EStructuralFeature_EJavaObject()
		p.InitEOperation(operation, nil, "eSet", 0, 1, true, true)
		p.AddEParameter(operation, nil, "feature", 0, 1, true, true)
		p.AddEParameter(operation, nil, "newValue", 0, 1, true, true)
	}
	{
		operation := p.GetEObject_EIsSet_EStructuralFeature()
		p.InitEOperation(operation, p.GetEBoolean(), "eIsSet", 0, 1, true, true)
		p.AddEParameter(operation, p.GetEStructuralFeature(), "feature", 0, 1, true, true)
	}
	{
		operation := p.GetEObject_EUnset_EStructuralFeature()
		p.InitEOperation(operation, nil, "eUnset", 0, 1, true, true)
		p.AddEParameter(operation, nil, "feature", 0, 1, true, true)
	}
	{
		operation := p.GetEObject_EInvoke_EOperation_EEList()
		p.InitEOperation(operation, p.GetEJavaObject(), "eInvoke", 0, 1, true, true)
		p.AddEParameter(operation, p.GetEOperation(), "operation", 0, 1, true, true)
		p.AddEParameter(operation, p.GetEEList(), "arguments", 0, 1, true, true)
	}

	p.InitEClass(p.eOperation, "EOperation", "ecore.EOperation", false, false)
	p.InitEAttribute(p.GetEOperation_OperationID(), p.GetEInt(), "operationID", "-1", 0, 1, false, false, true, false, true, false, true, false)
	p.InitEReference(p.GetEOperation_EContainingClass(), p.GetEClass(), p.GetEClass_EOperations(), "eContainingClass", "", 0, 1, true, false, false, false, false, false, true, false, true)
	p.InitEReference(p.GetEOperation_EParameters(), p.GetEParameter(), p.GetEParameter_EOperation(), "eParameters", "", 0, -1, false, false, true, true, false, false, true, false, true)
	p.InitEReference(p.GetEOperation_EExceptions(), p.GetEClassifierClass(), nil, "eExceptions", "", 0, -1, false, false, true, false, true, true, true, false, true)
	{
		operation := p.GetEOperation_IsOverrideOf_EOperation()
		p.InitEOperation(operation, p.GetEBoolean(), "isOverrideOf", 0, 1, true, true)
		p.AddEParameter(operation, p.GetEOperation(), "someOperation", 0, 1, true, true)
	}

	p.InitEClass(p.ePackage, "EPackage", "ecore.EPackage", false, false)
	p.InitEAttribute(p.GetEPackage_NsURI(), p.GetEString(), "nsURI", "", 0, 1, false, false, true, false, true, false, true, false)
	p.InitEAttribute(p.GetEPackage_NsPrefix(), p.GetEString(), "nsPrefix", "", 0, 1, false, false, true, false, true, false, true, false)
	p.InitEReference(p.GetEPackage_EFactoryInstance(), p.GetEFactory(), p.GetEFactory_EPackage(), "eFactoryInstance", "", 1, 1, true, false, true, true, false, false, true, false, true)
	p.InitEReference(p.GetEPackage_EClassifiers(), p.GetEClassifierClass(), p.GetEClassifier_EPackage(), "eClassifiers", "", 0, -1, false, false, true, true, true, false, true, false, true)
	p.InitEReference(p.GetEPackage_ESubPackages(), p.GetEPackage(), p.GetEPackage_ESuperPackage(), "eSubPackages", "", 0, -1, false, false, true, true, true, false, true, false, true)
	p.InitEReference(p.GetEPackage_ESuperPackage(), p.GetEPackage(), p.GetEPackage_ESubPackages(), "eSuperPackage", "", 0, 1, true, false, false, false, true, false, true, false, true)
	{
		operation := p.GetEPackage_GetEClassifier_EString()
		p.InitEOperation(operation, p.GetEClassifierClass(), "getEClassifier", 0, 1, true, true)
		p.AddEParameter(operation, p.GetEString(), "name", 0, 1, true, true)
	}

	p.InitEClass(p.eParameter, "EParameter", "ecore.EParameter", false, false)
	p.InitEReference(p.GetEParameter_EOperation(), p.GetEOperation(), p.GetEOperation_EParameters(), "eOperation", "", 0, 1, true, false, false, false, false, false, true, false, true)

	p.InitEClass(p.eReference, "EReference", "ecore.EReference", false, false)
	p.InitEAttribute(p.GetEReference_Containment(), p.GetEBoolean(), "containment", "", 0, 1, false, false, true, false, true, false, true, false)
	p.InitEAttribute(p.GetEReference_Container(), p.GetEBoolean(), "container", "", 0, 1, true, true, false, false, true, true, true, false)
	p.InitEAttribute(p.GetEReference_ResolveProxies(), p.GetEBoolean(), "resolveProxies", "true", 0, 1, false, false, true, false, true, false, true, false)
	p.InitEReference(p.GetEReference_EOpposite(), p.GetEReference(), nil, "eOpposite", "", 0, 1, false, false, true, false, true, false, true, false, true)
	p.InitEReference(p.GetEReference_EReferenceType(), p.GetEClass(), nil, "eReferenceType", "", 1, 1, true, true, false, false, true, false, true, true, true)
	p.InitEReference(p.GetEReference_EKeys(), p.GetEAttribute(), nil, "eKeys", "", 0, -1, false, false, true, false, true, false, true, false, true)

	p.InitEClass(p.eStringToStringMapEntry, "EStringToStringMapEntry", "ecore.EMapEntry", false, false)
	p.InitEAttribute(p.GetEStringToStringMapEntry_Key(), p.GetEString(), "key", "", 0, 1, false, false, true, false, true, false, true, false)
	p.InitEAttribute(p.GetEStringToStringMapEntry_Value(), p.GetEString(), "value", "", 0, 1, false, false, true, false, true, false, true, false)

	p.InitEClass(p.eStructuralFeature, "EStructuralFeature", "ecore.EStructuralFeature", true, false)
	p.InitEAttribute(p.GetEStructuralFeature_Changeable(), p.GetEBoolean(), "changeable", "true", 0, 1, false, false, true, false, true, false, true, false)
	p.InitEAttribute(p.GetEStructuralFeature_Volatile(), p.GetEBoolean(), "volatile", "", 0, 1, false, false, true, false, true, false, true, false)
	p.InitEAttribute(p.GetEStructuralFeature_Transient(), p.GetEBoolean(), "transient", "", 0, 1, false, false, true, false, true, false, true, false)
	p.InitEAttribute(p.GetEStructuralFeature_DefaultValueLiteral(), p.GetEString(), "defaultValueLiteral", "", 0, 1, false, false, true, false, true, false, true, false)
	p.InitEAttribute(p.GetEStructuralFeature_DefaultValue(), p.GetEJavaObject(), "defaultValue", "", 0, 1, true, true, true, false, true, true, true, false)
	p.InitEAttribute(p.GetEStructuralFeature_Unsettable(), p.GetEBoolean(), "unsettable", "", 0, 1, false, false, true, false, true, false, true, false)
	p.InitEAttribute(p.GetEStructuralFeature_Derived(), p.GetEBoolean(), "derived", "", 0, 1, false, false, true, false, true, false, true, false)
	p.InitEAttribute(p.GetEStructuralFeature_FeatureID(), p.GetEInt(), "featureID", "-1", 0, 1, false, false, true, false, true, false, true, false)
	p.InitEReference(p.GetEStructuralFeature_EContainingClass(), p.GetEClass(), p.GetEClass_EStructuralFeatures(), "eContainingClass", "", 0, 1, true, false, false, false, false, false, true, false, true)
	p.InitEOperation(p.GetEStructuralFeature_GetContainerClass(), p.GetEJavaClass(), "getContainerClass", 0, 1, true, true)

	p.InitEClass(p.eTypeParameter, "ETypeParameter", "ecore.ETypeParameter", false, false)
	p.InitEReference(p.GetETypeParameter_EBounds(), p.GetEGenericType(), nil, "eBounds", "", 0, -1, false, false, true, true, false, false, true, false, true)

	p.InitEClass(p.eTypedElement, "ETypedElement", "ecore.ETypedElement", true, false)
	p.InitEAttribute(p.GetETypedElement_Ordered(), p.GetEBoolean(), "ordered", "true", 0, 1, false, false, true, false, true, false, true, false)
	p.InitEAttribute(p.GetETypedElement_Unique(), p.GetEBoolean(), "unique", "true", 0, 1, false, false, true, false, true, false, true, false)
	p.InitEAttribute(p.GetETypedElement_LowerBound(), p.GetEInt(), "lowerBound", "", 0, 1, false, false, true, false, true, false, true, false)
	p.InitEAttribute(p.GetETypedElement_UpperBound(), p.GetEInt(), "upperBound", "1", 0, 1, false, false, true, false, true, false, true, false)
	p.InitEAttribute(p.GetETypedElement_Many(), p.GetEBoolean(), "many", "", 0, 1, true, true, false, false, true, true, true, false)
	p.InitEAttribute(p.GetETypedElement_Required(), p.GetEBoolean(), "required", "", 0, 1, true, true, false, false, true, true, true, false)
	p.InitEReference(p.GetETypedElement_EType(), p.GetEClassifierClass(), nil, "eType", "", 0, 1, false, false, true, false, true, true, true, false, true)

	p.InitEDataType(p.GetEBigDecimal(), "EBigDecimal", "float64", "0.0", true)
	p.InitEDataType(p.GetEBigInteger(), "EBigInteger", "int64", "0", true)
	p.InitEDataType(p.GetEBoolean(), "EBoolean", "bool", "false", true)
	p.InitEDataType(p.GetEBooleanObject(), "EBooleanObject", "bool", "false", true)
	p.InitEDataType(p.GetEByte(), "EByte", "byte", "0", true)
	p.InitEDataType(p.GetEByteArray(), "EByteArray", "[]byte", "", true)
	p.InitEDataType(p.GetEByteObject(), "EByteObject", "byte", "", true)
	p.InitEDataType(p.GetEChar(), "EChar", "byte", "", true)
	p.InitEDataType(p.GetECharacterObject(), "ECharacterObject", "byte", "", true)
	p.InitEDataType(p.GetEDate(), "EDate", "*time.Time", "", true)
	p.InitEDataType(p.GetEDiagnosticChain(), "EDiagnosticChain", "ecore.EDiagnosticChain", "", false)
	p.InitEDataType(p.GetEDouble(), "EDouble", "float64", "0.0", true)
	p.InitEDataType(p.GetEDoubleObject(), "EDoubleObject", "float64", "0.0", true)
	p.InitEDataType(p.GetEEList(), "EEList", "ecore.EList", "", false)
	p.InitEDataType(p.GetEEnumerator(), "EEnumerator", "interface{}", "", false)
	p.InitEDataType(p.GetEFeatureMap(), "EFeatureMap", "interface{}", "", false)
	p.InitEDataType(p.GetEFeatureMapEntry(), "EFeatureMapEntry", "interface{}", "", false)
	p.InitEDataType(p.GetEFloat(), "EFloat", "float32", "0.0", true)
	p.InitEDataType(p.GetEFloatObject(), "EFloatObject", "float32", "0.0", true)
	p.InitEDataType(p.GetEInt(), "EInt", "int", "0", true)
	p.InitEDataType(p.GetEIntegerObject(), "EIntegerObject", "int", "0", true)
	p.InitEDataType(p.GetEInvocationTargetException(), "EInvocationTargetException", "java.lang.reflect.InvocationTargetException", "", false)
	p.InitEDataType(p.GetEJavaClass(), "EJavaClass", "reflect.Type", "", true)
	p.InitEDataType(p.GetEJavaObject(), "EJavaObject", "interface{}", "", true)
	p.InitEDataType(p.GetELong(), "ELong", "int64", "0", true)
	p.InitEDataType(p.GetELongObject(), "ELongObject", "int", "0", true)
	p.InitEDataType(p.GetEMap(), "EMap", "ecore.EMap", "", false)
	p.InitEDataType(p.GetEResource(), "EResource", "ecore.EResource", "", false)
	p.InitEDataType(p.GetEResourceSet(), "EResourceSet", "ecore.EResourceSet", "", false)
	p.InitEDataType(p.GetEShort(), "EShort", "int16", "0", true)
	p.InitEDataType(p.GetEShortObject(), "EShortObject", "int16", "0", true)
	p.InitEDataType(p.GetEString(), "EString", "string", "", true)
	p.InitEDataType(p.GetETreeIterator(), "ETreeIterator", "ecore.EIterator", "", false)

}
