// *****************************************************************************
//
// This file is part of a MASA library or program.
// Refer to the included end-user license agreement for restrictions.
//
// Copyright (c) 2020 MASA Group
//
// *****************************************************************************

// *****************************************************************************
//
// Warning: This file was generated by soft.generator.go Generator
//
// *****************************************************************************

package ecore

import (
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"testing"
)

func discardEEnum() {
	_ = assert.Equal
	_ = mock.Anything
	_ = testing.Coverage

}

func TestEEnumELiteralsGetList(t *testing.T) {
	obj := newEEnumImpl()
	assert.NotNil(t, obj.GetELiterals())
}

func TestEEnumGetEEnumLiteralByNameOperation(t *testing.T) {
	obj := newEEnumImpl()
	assert.Panics(t, func() { obj.GetEEnumLiteralByName("") })
}
func TestEEnumGetEEnumLiteralByValueOperation(t *testing.T) {
	obj := newEEnumImpl()
	assert.Panics(t, func() { obj.GetEEnumLiteralByValue(0) })
}
func TestEEnumGetEEnumLiteralByLiteralOperation(t *testing.T) {
	obj := newEEnumImpl()
	assert.Panics(t, func() { obj.GetEEnumLiteralByLiteral("") })
}
