// Code generated by soft.generator.go. DO NOT EDIT.

// *****************************************************************************
// Copyright(c) 2021 MASA Group
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// *****************************************************************************

package ecore

type MockEFactory struct {
	MockEModelElement
}

// GetEPackage get the value of ePackage
func (eFactory *MockEFactory) GetEPackage() EPackage {
	ret := eFactory.Called()

	var r EPackage
	if rf, ok := ret.Get(0).(func() EPackage); ok {
		r = rf()
	} else {
		if ret.Get(0) != nil {
			r = ret.Get(0).(EPackage)
		}
	}

	return r
}

// SetEPackage provides mock implementation for setting the value of ePackage
func (eFactory *MockEFactory) SetEPackage(newEPackage EPackage) {
	eFactory.Called(newEPackage)
}

// ConvertToString provides mock implementation
func (eFactory *MockEFactory) ConvertToString(eDataType EDataType, instanceValue interface{}) string {
	ret := eFactory.Called(eDataType, instanceValue)

	var r string
	if rf, ok := ret.Get(0).(func() string); ok {
		r = rf()
	} else {
		if ret.Get(0) != nil {
			r = ret.Get(0).(string)
		}
	}

	return r
}

// Create provides mock implementation
func (eFactory *MockEFactory) Create(eClass EClass) EObject {
	ret := eFactory.Called(eClass)

	var r EObject
	if rf, ok := ret.Get(0).(func() EObject); ok {
		r = rf()
	} else {
		if ret.Get(0) != nil {
			r = ret.Get(0).(EObject)
		}
	}

	return r
}

// CreateFromString provides mock implementation
func (eFactory *MockEFactory) CreateFromString(eDataType EDataType, literalValue string) interface{} {
	ret := eFactory.Called(eDataType, literalValue)

	var r interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r = rf()
	} else {
		if ret.Get(0) != nil {
			r = ret.Get(0).(interface{})
		}
	}

	return r
}
