package ecore

// MockEObjectList is an autogenerated mock type for the EObjectList type
type MockEObjectList struct {
	MockEList
}

// GetUnResolvedList provides a mock function with given fields:
func (_m *MockEObjectList) GetUnResolvedList() EList {
	ret := _m.Called()

	var r0 EList
	if rf, ok := ret.Get(0).(func() EList); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(EList)
		}
	}

	return r0
}
