// *****************************************************************************
//
// This file is part of a MASA library or program.
// Refer to the included end-user license agreement for restrictions.
//
// Copyright (c) 2020 MASA Group
//
// *****************************************************************************

// *****************************************************************************
//
// Warning: This file was generated by soft.generator.go Generator
//
// *****************************************************************************

package ecore

import (
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"testing"
)

func discardEObject() {
	_ = assert.Equal
	_ = mock.Anything
	_ = testing.Coverage
}

func TestEObjectAsEObject(t *testing.T) {
	o := NewEObjectImpl()
	assert.Equal(t, o, o.asEObject())
}

func TestEObjectStaticClass(t *testing.T) {
	o := NewEObjectImpl()
	assert.Equal(t, GetPackage().GetEObject(), o.EStaticClass())
}

func TestEObjectFeatureCount(t *testing.T) {
	o := NewEObjectImpl()
	assert.Equal(t, EOBJECT_FEATURE_COUNT, o.EStaticFeatureCount())
}
