// Code generated by mockery v1.0.0. DO NOT EDIT.

package ecore

import mock "github.com/stretchr/testify/mock"

// MockEPackageRegistry is an autogenerated mock type for the EPackageRegistry type
type MockEPackageRegistry struct {
	mock.Mock
}

// GetFactory provides a mock function with given fields: nsURI
func (_m *MockEPackageRegistry) GetFactory(nsURI string) EFactory {
	ret := _m.Called(nsURI)

	var r0 EFactory
	if rf, ok := ret.Get(0).(func(string) EFactory); ok {
		r0 = rf(nsURI)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(EFactory)
		}
	}

	return r0
}

// GetPackage provides a mock function with given fields: nsURI
func (_m *MockEPackageRegistry) GetPackage(nsURI string) EPackage {
	ret := _m.Called(nsURI)

	var r0 EPackage
	if rf, ok := ret.Get(0).(func(string) EPackage); ok {
		r0 = rf(nsURI)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(EPackage)
		}
	}

	return r0
}

// RegisterPackage provides a mock function with given fields: pack
func (_m *MockEPackageRegistry) RegisterPackage(pack EPackage) {
	_m.Called(pack)
}

// UnregisterPackage provides a mock function with given fields: pack
func (_m *MockEPackageRegistry) UnregisterPackage(pack EPackage) {
	_m.Called(pack)
}
