// *****************************************************************************
//
// This file is part of a MASA library or program.
// Refer to the included end-user license agreement for restrictions.
//
// Copyright (c) 2020 MASA Group
//
// *****************************************************************************

// *****************************************************************************
//
// Warning: This file was generated by soft.generator.go Generator
//
// *****************************************************************************

package ecore

import (
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"testing"
)

func discardEPackage() {
	_ = assert.Equal
	_ = mock.Anything
	_ = testing.Coverage

}

func TestEPackageNsURIGet(t *testing.T) {
	var newValue string = "Test String"
	obj := newEPackageImpl()
	obj.SetNsURI(newValue)
	assert.Equal(t, newValue, obj.GetNsURI())
}

func TestEPackageNsURISet(t *testing.T) {
	var newValue string = "Test String"
	obj := newEPackageImpl()
	mockAdapter := &MockEAdapter{}
	mockAdapter.On("SetTarget", obj).Once()
	mockAdapter.On("NotifyChanged", mock.Anything).Once()
	obj.EAdapters().Add(mockAdapter)
	obj.SetNsURI(newValue)
	mockAdapter.AssertExpectations(t)
}

func TestEPackageNsPrefixGet(t *testing.T) {
	var newValue string = "Test String"
	obj := newEPackageImpl()
	obj.SetNsPrefix(newValue)
	assert.Equal(t, newValue, obj.GetNsPrefix())
}

func TestEPackageNsPrefixSet(t *testing.T) {
	var newValue string = "Test String"
	obj := newEPackageImpl()
	mockAdapter := &MockEAdapter{}
	mockAdapter.On("SetTarget", obj).Once()
	mockAdapter.On("NotifyChanged", mock.Anything).Once()
	obj.EAdapters().Add(mockAdapter)
	obj.SetNsPrefix(newValue)
	mockAdapter.AssertExpectations(t)
}

func TestEPackageEFactoryInstanceSet(t *testing.T) {
	var newValue *MockEFactory = &MockEFactory{}
	obj := newEPackageImpl()
	mockAdapter := &MockEAdapter{}
	mockAdapter.On("SetTarget", obj).Once()
	mockAdapter.On("NotifyChanged", mock.Anything).Once()
	obj.EAdapters().Add(mockAdapter)
	obj.SetEFactoryInstance(newValue)
	mockAdapter.AssertExpectations(t)
}

func TestEPackageEClassifiersGetList(t *testing.T) {
	obj := newEPackageImpl()
	assert.NotNil(t, obj.GetEClassifiers())
}

func TestEPackageESubPackagesGetList(t *testing.T) {
	obj := newEPackageImpl()
	assert.NotNil(t, obj.GetESubPackages())
}

func TestEPackageGetEClassifierOperation(t *testing.T) {
	obj := newEPackageImpl()
	assert.Panics(t, func() { obj.GetEClassifier("") })
}
