// *****************************************************************************
//
// This file is part of a MASA library or program.
// Refer to the included end-user license agreement for restrictions.
//
// Copyright (c) 2020 MASA Group
//
// *****************************************************************************

// *****************************************************************************
//
// Warning: This file was generated by soft.generator.go Generator
//
// *****************************************************************************

package ecore

import (
	"github.com/stretchr/testify/assert"
	"testing"
)

func discardMockEPackage() {
	_ = assert.Equal
	_ = testing.Coverage
}

// TestMockEPackageGetEClassifiers tests method GetEClassifiers
func TestMockEPackageGetEClassifiers(t *testing.T) {
	o := &MockEPackage{}
	l := &MockEList{}
	// return a value
	o.On("GetEClassifiers").Once().Return(l)
	o.On("GetEClassifiers").Once().Return(func() EList {
		return l
	})
	assert.Equal(t, l, o.GetEClassifiers())
	assert.Equal(t, l, o.GetEClassifiers())
	o.AssertExpectations(t)
}

// TestMockEPackageGetEFactoryInstance tests method GetEFactoryInstance
func TestMockEPackageGetEFactoryInstance(t *testing.T) {
	o := &MockEPackage{}
	r := new(MockEFactory)
	o.On("GetEFactoryInstance").Once().Return(r)
	o.On("GetEFactoryInstance").Once().Return(func() EFactory {
		return r
	})
	assert.Equal(t, r, o.GetEFactoryInstance())
	assert.Equal(t, r, o.GetEFactoryInstance())
	o.AssertExpectations(t)
}

// TestMockEPackageSetEFactoryInstance tests method SetEFactoryInstance
func TestMockEPackageSetEFactoryInstance(t *testing.T) {
	o := &MockEPackage{}
	v := new(MockEFactory)
	o.On("SetEFactoryInstance", v).Once()
	o.SetEFactoryInstance(v)
	o.AssertExpectations(t)
}

// TestMockEPackageGetESubPackages tests method GetESubPackages
func TestMockEPackageGetESubPackages(t *testing.T) {
	o := &MockEPackage{}
	l := &MockEList{}
	// return a value
	o.On("GetESubPackages").Once().Return(l)
	o.On("GetESubPackages").Once().Return(func() EList {
		return l
	})
	assert.Equal(t, l, o.GetESubPackages())
	assert.Equal(t, l, o.GetESubPackages())
	o.AssertExpectations(t)
}

// TestMockEPackageGetESuperPackage tests method GetESuperPackage
func TestMockEPackageGetESuperPackage(t *testing.T) {
	o := &MockEPackage{}
	r := new(MockEPackage)
	o.On("GetESuperPackage").Once().Return(r)
	o.On("GetESuperPackage").Once().Return(func() EPackage {
		return r
	})
	assert.Equal(t, r, o.GetESuperPackage())
	assert.Equal(t, r, o.GetESuperPackage())
	o.AssertExpectations(t)
}

// TestMockEPackageGetNsPrefix tests method GetNsPrefix
func TestMockEPackageGetNsPrefix(t *testing.T) {
	o := &MockEPackage{}
	r := "Test String"
	o.On("GetNsPrefix").Once().Return(r)
	o.On("GetNsPrefix").Once().Return(func() string {
		return r
	})
	assert.Equal(t, r, o.GetNsPrefix())
	assert.Equal(t, r, o.GetNsPrefix())
	o.AssertExpectations(t)
}

// TestMockEPackageSetNsPrefix tests method SetNsPrefix
func TestMockEPackageSetNsPrefix(t *testing.T) {
	o := &MockEPackage{}
	v := "Test String"
	o.On("SetNsPrefix", v).Once()
	o.SetNsPrefix(v)
	o.AssertExpectations(t)
}

// TestMockEPackageGetNsURI tests method GetNsURI
func TestMockEPackageGetNsURI(t *testing.T) {
	o := &MockEPackage{}
	r := "Test String"
	o.On("GetNsURI").Once().Return(r)
	o.On("GetNsURI").Once().Return(func() string {
		return r
	})
	assert.Equal(t, r, o.GetNsURI())
	assert.Equal(t, r, o.GetNsURI())
	o.AssertExpectations(t)
}

// TestMockEPackageSetNsURI tests method SetNsURI
func TestMockEPackageSetNsURI(t *testing.T) {
	o := &MockEPackage{}
	v := "Test String"
	o.On("SetNsURI", v).Once()
	o.SetNsURI(v)
	o.AssertExpectations(t)
}

// TestMockEPackageGetEClassifier tests method GetEClassifier
func TestMockEPackageGetEClassifier(t *testing.T) {
	o := &MockEPackage{}
	name := "Test String"
	r := new(MockEClassifier)
	o.On("GetEClassifier", name).Return(r).Once()
	o.On("GetEClassifier", name).Return(func() EClassifier {
		return r
	}).Once()
	assert.Equal(t, r, o.GetEClassifier(name))
	assert.Equal(t, r, o.GetEClassifier(name))
	o.AssertExpectations(t)
}
