// *****************************************************************************
//
// This file is part of a MASA library or program.
// Refer to the included end-user license agreement for restrictions.
//
// Copyright (c) 2020 MASA Group
//
// *****************************************************************************

// *****************************************************************************
//
// Warning: This file was generated by soft.generator.go Generator
//
// *****************************************************************************

package ecore

import (
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"testing"
)

func discardEParameter() {
	_ = assert.Equal
	_ = mock.Anything
	_ = testing.Coverage
}

func TestEParameterAsEParameter(t *testing.T) {
	o := newEParameterImpl()
	assert.Equal(t, o, o.asEParameter())
}

func TestEParameterStaticClass(t *testing.T) {
	o := newEParameterImpl()
	assert.Equal(t, GetPackage().GetEParameter(), o.EStaticClass())
}

func TestEParameterFeatureCount(t *testing.T) {
	o := newEParameterImpl()
	assert.Equal(t, EPARAMETER_FEATURE_COUNT, o.EStaticFeatureCount())
}

func TestEParameterEOperationGet(t *testing.T) {
	// default
	o := newEParameterImpl()
	assert.Nil(t, o.GetEOperation())

	// set a mock container
	v := new(MockEOperation)
	o.ESetInternalContainer(v, EPARAMETER__EOPERATION)

	// no proxy
	v.On("EIsProxy").Return(false)
	assert.Equal(t, v, o.GetEOperation())
}

func TestEParameterEGetFromID(t *testing.T) {
	o := newEParameterImpl()
	assert.Panics(t, func() { o.EGetFromID(-1, true) })
	assert.Equal(t, o.GetEOperation(), o.EGetFromID(EPARAMETER__EOPERATION, true))
}

func TestEParameterEIsSetFromID(t *testing.T) {
	o := newEParameterImpl()
	assert.Panics(t, func() { o.EIsSetFromID(-1) })
	assert.False(t, o.EIsSetFromID(EPARAMETER__EOPERATION))
}
