// *****************************************************************************
//
// This file is part of a MASA library or program.
// Refer to the included end-user license agreement for restrictions.
//
// Copyright (c) 2020 MASA Group
//
// *****************************************************************************

// *****************************************************************************
//
// Warning: This file was generated by soft.generator.go Generator
//
// *****************************************************************************

package ecore

type MockEStringToStringMapEntry struct {
	MockEObjectInternal
}

// GetKey get the value of key
func (eStringToStringMapEntry *MockEStringToStringMapEntry) GetKey() string {
	ret := eStringToStringMapEntry.Called()

	var r string
	if rf, ok := ret.Get(0).(func() string); ok {
		r = rf()
	} else {
		if ret.Get(0) != nil {
			r = ret.Get(0).(string)
		}
	}

	return r
}

// SetKey provides mock implementation for setting the value of key
func (eStringToStringMapEntry *MockEStringToStringMapEntry) SetKey(newKey string) {
	eStringToStringMapEntry.Called(newKey)
}

// GetValue get the value of value
func (eStringToStringMapEntry *MockEStringToStringMapEntry) GetValue() string {
	ret := eStringToStringMapEntry.Called()

	var r string
	if rf, ok := ret.Get(0).(func() string); ok {
		r = rf()
	} else {
		if ret.Get(0) != nil {
			r = ret.Get(0).(string)
		}
	}

	return r
}

// SetValue provides mock implementation for setting the value of value
func (eStringToStringMapEntry *MockEStringToStringMapEntry) SetValue(newValue string) {
	eStringToStringMapEntry.Called(newValue)
}
