// *****************************************************************************
//
// This file is part of a MASA library or program.
// Refer to the included end-user license agreement for restrictions.
//
// Copyright (c) 2020 MASA Group
//
// *****************************************************************************

// *****************************************************************************
//
// Warning: This file was generated by soft.generator.go Generator
//
// *****************************************************************************

package ecore

import (
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"testing"
)

func discardEStructuralFeature() {
	_ = assert.Equal
	_ = mock.Anything
	_ = testing.Coverage

}

func TestEStructuralFeatureChangeableGet(t *testing.T) {
	var newValue bool = true
	obj := newEStructuralFeatureImpl()
	obj.SetChangeable(newValue)
	assert.Equal(t, newValue, obj.IsChangeable())
}

func TestEStructuralFeatureChangeableSet(t *testing.T) {
	var newValue bool = true
	obj := newEStructuralFeatureImpl()
	mockAdapter := &MockEAdapter{}
	mockAdapter.On("SetTarget", obj).Once()
	mockAdapter.On("NotifyChanged", mock.Anything).Once()
	obj.EAdapters().Add(mockAdapter)
	obj.SetChangeable(newValue)
	mockAdapter.AssertExpectations(t)
}

func TestEStructuralFeatureVolatileGet(t *testing.T) {
	var newValue bool = true
	obj := newEStructuralFeatureImpl()
	obj.SetVolatile(newValue)
	assert.Equal(t, newValue, obj.IsVolatile())
}

func TestEStructuralFeatureVolatileSet(t *testing.T) {
	var newValue bool = true
	obj := newEStructuralFeatureImpl()
	mockAdapter := &MockEAdapter{}
	mockAdapter.On("SetTarget", obj).Once()
	mockAdapter.On("NotifyChanged", mock.Anything).Once()
	obj.EAdapters().Add(mockAdapter)
	obj.SetVolatile(newValue)
	mockAdapter.AssertExpectations(t)
}

func TestEStructuralFeatureTransientGet(t *testing.T) {
	var newValue bool = true
	obj := newEStructuralFeatureImpl()
	obj.SetTransient(newValue)
	assert.Equal(t, newValue, obj.IsTransient())
}

func TestEStructuralFeatureTransientSet(t *testing.T) {
	var newValue bool = true
	obj := newEStructuralFeatureImpl()
	mockAdapter := &MockEAdapter{}
	mockAdapter.On("SetTarget", obj).Once()
	mockAdapter.On("NotifyChanged", mock.Anything).Once()
	obj.EAdapters().Add(mockAdapter)
	obj.SetTransient(newValue)
	mockAdapter.AssertExpectations(t)
}

func TestEStructuralFeatureDefaultValueLiteralGet(t *testing.T) {
	var newValue string = "Test String"
	obj := newEStructuralFeatureImpl()
	obj.SetDefaultValueLiteral(newValue)
	assert.Equal(t, newValue, obj.GetDefaultValueLiteral())
}

func TestEStructuralFeatureDefaultValueLiteralSet(t *testing.T) {
	var newValue string = "Test String"
	obj := newEStructuralFeatureImpl()
	mockAdapter := &MockEAdapter{}
	mockAdapter.On("SetTarget", obj).Once()
	mockAdapter.On("NotifyChanged", mock.Anything).Once()
	obj.EAdapters().Add(mockAdapter)
	obj.SetDefaultValueLiteral(newValue)
	mockAdapter.AssertExpectations(t)
}

func TestEStructuralFeatureUnsettableGet(t *testing.T) {
	var newValue bool = true
	obj := newEStructuralFeatureImpl()
	obj.SetUnsettable(newValue)
	assert.Equal(t, newValue, obj.IsUnsettable())
}

func TestEStructuralFeatureUnsettableSet(t *testing.T) {
	var newValue bool = true
	obj := newEStructuralFeatureImpl()
	mockAdapter := &MockEAdapter{}
	mockAdapter.On("SetTarget", obj).Once()
	mockAdapter.On("NotifyChanged", mock.Anything).Once()
	obj.EAdapters().Add(mockAdapter)
	obj.SetUnsettable(newValue)
	mockAdapter.AssertExpectations(t)
}

func TestEStructuralFeatureDerivedGet(t *testing.T) {
	var newValue bool = true
	obj := newEStructuralFeatureImpl()
	obj.SetDerived(newValue)
	assert.Equal(t, newValue, obj.IsDerived())
}

func TestEStructuralFeatureDerivedSet(t *testing.T) {
	var newValue bool = true
	obj := newEStructuralFeatureImpl()
	mockAdapter := &MockEAdapter{}
	mockAdapter.On("SetTarget", obj).Once()
	mockAdapter.On("NotifyChanged", mock.Anything).Once()
	obj.EAdapters().Add(mockAdapter)
	obj.SetDerived(newValue)
	mockAdapter.AssertExpectations(t)
}

func TestEStructuralFeatureFeatureIDGet(t *testing.T) {
	var newValue int = 45
	obj := newEStructuralFeatureImpl()
	obj.SetFeatureID(newValue)
	assert.Equal(t, newValue, obj.GetFeatureID())
}

func TestEStructuralFeatureFeatureIDSet(t *testing.T) {
	var newValue int = 45
	obj := newEStructuralFeatureImpl()
	mockAdapter := &MockEAdapter{}
	mockAdapter.On("SetTarget", obj).Once()
	mockAdapter.On("NotifyChanged", mock.Anything).Once()
	obj.EAdapters().Add(mockAdapter)
	obj.SetFeatureID(newValue)
	mockAdapter.AssertExpectations(t)
}

func TestEStructuralFeatureGetContainerClassOperation(t *testing.T) {
	obj := newEStructuralFeatureImpl()
	assert.Panics(t, func() { obj.GetContainerClass() })
}
