// *****************************************************************************
//
// This file is part of a MASA library or program.
// Refer to the included end-user license agreement for restrictions.
//
// Copyright (c) 2020 MASA Group
//
// *****************************************************************************

// *****************************************************************************
//
// Warning: This file was generated by soft.generator.go Generator
//
// *****************************************************************************

package ecore

// EStringToStringMapEntry is the representation of the model object 'EStringToStringMapEntry'
type EStringToStringMapEntry interface {
	EObject
	EMapEntry

	GetStringKey() string
	SetStringKey(string)

	GetStringValue() string
	SetStringValue(string)

	// Start of user code EStringToStringMapEntry
	// End of user code
}
