// Code generated by soft.generator.go. DO NOT EDIT.

// *****************************************************************************
// Copyright(c) 2021 MASA Group
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// *****************************************************************************

package ecore

import (
	"github.com/stretchr/testify/assert"
	"testing"
)

func discardMockEStringToStringMapEntry() {
	_ = assert.Equal
	_ = testing.Coverage
}

// TestMockEStringToStringMapEntryGetTypedKey tests method GetTypedKey
func TestMockEStringToStringMapEntryGetTypedKey(t *testing.T) {
	o := &MockEStringToStringMapEntry{}
	r := string("Test String")
	o.On("GetTypedKey").Once().Return(r)
	o.On("GetTypedKey").Once().Return(func() string {
		return r
	})
	assert.Equal(t, r, o.GetTypedKey())
	assert.Equal(t, r, o.GetTypedKey())
	o.AssertExpectations(t)
}

// TestMockEStringToStringMapEntrySetTypedKey tests method SetTypedKey
func TestMockEStringToStringMapEntrySetTypedKey(t *testing.T) {
	o := &MockEStringToStringMapEntry{}
	v := string("Test String")
	o.On("SetTypedKey", v).Once()
	o.SetTypedKey(v)
	o.AssertExpectations(t)
}

// TestMockEStringToStringMapEntryGetTypedValue tests method GetTypedValue
func TestMockEStringToStringMapEntryGetTypedValue(t *testing.T) {
	o := &MockEStringToStringMapEntry{}
	r := string("Test String")
	o.On("GetTypedValue").Once().Return(r)
	o.On("GetTypedValue").Once().Return(func() string {
		return r
	})
	assert.Equal(t, r, o.GetTypedValue())
	assert.Equal(t, r, o.GetTypedValue())
	o.AssertExpectations(t)
}

// TestMockEStringToStringMapEntrySetTypedValue tests method SetTypedValue
func TestMockEStringToStringMapEntrySetTypedValue(t *testing.T) {
	o := &MockEStringToStringMapEntry{}
	v := string("Test String")
	o.On("SetTypedValue", v).Once()
	o.SetTypedValue(v)
	o.AssertExpectations(t)
}
