// Code generated by soft.generator.go. DO NOT EDIT.

// *****************************************************************************
// Copyright(c) 2021 MASA Group
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// *****************************************************************************

package ecore

// ETypeParameter is the representation of the model object 'ETypeParameter'
type ETypeParameter interface {
	ENamedElement

	GetEBounds() EList

	// Start of user code ETypeParameter
	// End of user code
}
