// Code generated by soft.generator.go. DO NOT EDIT.

// *****************************************************************************
// Copyright(c) 2021 MASA Group
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// *****************************************************************************

package ecore

import (
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"testing"
)

func discardMockETypeParameter() {
	_ = assert.Equal
	_ = testing.Coverage
}

type mockETypeParameterRun struct {
	mock.Mock
}

func (m *mockETypeParameterRun) Run(args ...any) {
	m.Called(args...)
}

type mockConstructorTestingTmockETypeParameterRun interface {
	mock.TestingT
	Cleanup(func())
}

// newMockETypeParameterRun creates a new instance of mockETypeParameterRun. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockETypeParameterRun(t mockConstructorTestingTmockETypeParameterRun, args ...any) *mockETypeParameterRun {
	mock := &mockETypeParameterRun{}
	mock.Test(t)
	mock.On("Run", args...).Once()
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}

// TestMockETypeParameterGetEBounds tests method GetEBounds
func TestMockETypeParameterGetEBounds(t *testing.T) {
	o := &MockETypeParameter{}
	l := &MockEList{}
	m := newMockETypeParameterRun(t)
	o.EXPECT().GetEBounds().Run(func() { m.Run() }).Return(l).Once()
	o.EXPECT().GetEBounds().Once().Return(func() EList { return l })
	assert.Equal(t, l, o.GetEBounds())
	assert.Equal(t, l, o.GetEBounds())
}
