// Code generated by soft.generator.go. DO NOT EDIT.

// *****************************************************************************
// Copyright(c) 2021 MASA Group
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// *****************************************************************************

package ecore

import (
	"github.com/stretchr/testify/assert"
	"testing"
)

func discardMockETypeParameter() {
	_ = assert.Equal
	_ = testing.Coverage
}

// TestMockETypeParameterGetEBounds tests method GetEBounds
func TestMockETypeParameterGetEBounds(t *testing.T) {
	o := &MockETypeParameter{}
	l := &MockEList{}
	// return a value
	o.On("GetEBounds").Once().Return(l)
	o.On("GetEBounds").Once().Return(func() EList {
		return l
	})
	assert.Equal(t, l, o.GetEBounds())
	assert.Equal(t, l, o.GetEBounds())
	o.AssertExpectations(t)
}
